(function(g){var window=this;var gAa=function(a,b){return g.Tb(a,b)},Z5=function(a){g.Em(a,"zx",g.xb());
return a},$5=function(a,b,c){g.ya(c)||(c=[String(c)]);
g.Hm(a.g,b,c)},hAa=function(a,b){var c=[];
g.mk(b,function(a){try{var b=g.ZC.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.YC(b)&&c.push(a):c.push(a)},a);
return c},iAa=function(a,b){var c=hAa(a,b);
(0,g.C)(c,function(a){g.ZC.prototype.remove.call(this,a)},a)},jAa=function(a,b,c,d){var e=new g.vm(null,void 0);
a&&g.wm(e,a);b&&g.xm(e,b);c&&g.ym(e,c);d&&g.zm(e,d);return e},kAa=function(a){g.OF[a]&&(a=g.OF[a],(0,g.C)(a,function(a){g.MF[a]&&delete g.MF[a]}),a.length=0)},lAa=function(a){var b=g.LF();
if(b)if(b.clear(a),a)kAa(a);else for(var c in g.OF)kAa(c)},mAa=function(){var a=(0,g.xG)();
a&&iAa(a,a.g.fe(!0))},a6=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.pm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",nAa(this,a.capabilities||""),oAa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},nAa=function(a,b){a.capabilities.clear();
(0,g.Gd)(b.split(","),g.Ea(gAa,pAa)).forEach(function(b){a.capabilities.add(b)})},oAa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},b6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},c6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},qAa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},rAa=function(a){return new b6(a)},sAa=function(a){return g.ya(a)?(0,g.H)(a,rAa):[]},d6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},e6=function(a){return g.ya(a)?"["+(0,g.H)(a,d6).join(",")+"]":"null"},f6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},tAa=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},g6=function(a,b){return g.La(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},h6=function(a,b){return g.La(a,function(a){return c6(a,b)})},i6=function(){var a=g.AG("yt-remote-connected-devices")||[];
g.fb(a);return a},uAa=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(a,b){return 0==b?a:a.substring(c.length)})},vAa=function(a){g.zG("yt-remote-connected-devices",a,86400)},k6=function(){if(j6)return j6;
var a=g.AG("yt-remote-device-id");a||(a=f6(),g.zG("yt-remote-device-id",a,31536E3));for(var b=i6(),c=1,d=a;g.Pa(b,d);)c++,d=a+"#"+c;return j6=d},l6=function(){var a=i6(),b=k6();
g.Pa(a,b);g.FG()&&g.ib(a,b);a=uAa(a);if(g.Qa(a))try{g.DG.remove("remote_sid","/","youtube.com")}catch(c){}else try{g.EG("remote_sid",a.join(","),-1)}catch(c){}},wAa=function(){return g.AG("yt-remote-session-browser-channel")},xAa=function(){return g.AG("yt-remote-local-screens")||[]},yAa=function(){g.zG("yt-remote-lounge-token-expiration",!0,86400)},zAa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)(xAa(),function(a){return a.loungeToken}),c=(0,g.H)(a,function(a){return a.loungeToken});
(0,g.em)(c,function(a){return!g.Pa(b,a)})&&yAa();
g.zG("yt-remote-local-screens",a,31536E3)},AAa=function(a,b){g.zG("yt-remote-session-browser-channel",a);
g.zG("yt-remote-session-screen-id",b);var c=i6(),d=k6();g.Pa(c,d)||c.push(d);vAa(c);l6()},m6=function(a){a||(g.BG("yt-remote-session-screen-id"),g.BG("yt-remote-session-video-id"));
l6();a=i6();g.Ua(a,k6());vAa(a)},BAa=function(){if(!n6){var a=g.eD();
a&&(n6=new g.TC(a))}return n6?!!n6.get("yt-remote-use-staging-server"):!1},CAa=function(){var a=window.document.createElement("a");
g.Vc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Cb(a)},DAa=function(a,b){var c=g.yd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Wc(c,g.$d("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},EAa=function(){var a=CAa(),b=window.document.getElementById(a),c=b&&g.$E(b,"loaded");
c||b&&!c||(b=DAa(a,function(){g.$E(b,"loaded")||(g.ZE(b,"loaded","true"),g.SF(a),g.ND(g.Ea(lAa,a),0))}))},o6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},FAa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},p6=function(a){a.length?GAa(a.shift(),function(){p6(a)}):q6()},HAa=function(a){return"chrome-extension://"+a+r6},GAa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},s6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},q6=function(){var a=FAa();
a&&a(!1,"No cast extension found")},t6=function(){if(IAa){var a=2,b=FAa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;GAa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",q6,c)}},JAa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(t6(),a({command:"cast.sender.init"}))},KAa=function(){t6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);p6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+r6,"//www.gstatic.com/eureka/clank"+r6])},u6=function(a,b,c){g.K.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.dd=b;this.B=(0,g.z)(this.gI,this);this.g=!1;this.l=0;this.o=this.xa=null;this.A=[]},v6=function(){},w6=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Lm(this);this.l=new g.qg;this.l.setInterval(250)},MAa=function(a,b,c){a.tj=1;
a.nh=Z5(b.clone());a.Ii=c;a.C=!0;LAa(a,null)},x6=function(a,b,c,d,e){a.tj=1;
a.nh=Z5(b.clone());a.Ii=null;a.C=c;e&&(a.EC=!1);LAa(a,d)},LAa=function(a,b){a.Xj=(0,g.G)();
y6(a);a.Fh=a.nh.clone();$5(a.Fh,"t",a.D);a.Wl=0;a.Qc=a.g.Rq(a.g.Pl()?b:null);0<a.xr&&(a.bp=new g.Ok((0,g.z)(a.TD,a,a.Qc),a.xr));a.A.R(a.Qc,"readystatechange",a.kT);var c=a.ji?g.$b(a.ji):{};a.Ii?(a.Jp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Qc.send(a.Fh,a.Jp,a.Ii,c)):(a.Jp="GET",a.EC&&!g.ud&&(c.Connection="close"),a.Qc.send(a.Fh,a.Jp,null,c));a.g.rf(1)},PAa=function(a,b,c){for(var d=!0;!a.Sh&&a.Wl<c.length;){var e=NAa(a,c);
if(e==z6){4==b&&(a.oh=4,A6(15),d=!1);break}else if(e==OAa){a.oh=4;A6(16);d=!1;break}else B6(a,e)}4==b&&0==c.length&&(a.oh=1,A6(17),d=!1);a.wf=a.wf&&d;d||(C6(a),D6(a))},NAa=function(a,b){var c=a.Wl,d=b.indexOf("\n",c);
if(-1==d)return z6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return OAa;d+=1;if(d+c>b.length)return z6;var e=b.substr(d,c);a.Wl=d+c;return e},RAa=function(a,b){a.Xj=(0,g.G)();
y6(a);var c=b?window.location.hostname:"";a.Fh=a.nh.clone();g.Em(a.Fh,"DOMAIN",c);g.Em(a.Fh,"t",a.D);try{a.xf=new window.ActiveXObject("htmlfile")}catch(n){C6(a);a.oh=7;A6(22);D6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in E6)k=E6[l];else if(l in QAa)k=E6[l]=QAa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=E6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Xc(g.sc("b/12014412"),d);a.xf.open();a.xf.write(g.Nc(c));a.xf.close();a.xf.parentWindow.m=(0,g.z)(a.oS,a);a.xf.parentWindow.d=(0,g.z)(a.UB,a,!0);a.xf.parentWindow.rpcClose=(0,g.z)(a.UB,a,!1);c=a.xf.createElement("DIV");a.xf.parentWindow.document.body.appendChild(c);d=g.Ec(a.Fh.toString());d=g.pb(g.Bc(d));d=g.Xc(g.sc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Nc(d);
a.g.rf(1)},y6=function(a){a.gv=(0,g.G)()+a.B;
SAa(a,a.B)},SAa=function(a,b){if(null!=a.sk)throw Error("WatchDog timer not null");
a.sk=F6((0,g.z)(a.FS,a),b)},G6=function(a){a.sk&&(g.w.clearTimeout(a.sk),a.sk=null)},D6=function(a){a.g.gy()||a.Sh||a.g.No(a)},C6=function(a){G6(a);
g.Ye(a.bp);a.bp=null;a.l.stop();g.Rm(a.A);if(a.Qc){var b=a.Qc;a.Qc=null;b.abort();b.dispose()}a.xf&&(a.xf=null)},B6=function(a,b){try{a.g.NB(a,b),a.g.rf(4)}catch(c){}},UAa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;TAa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){UAa(a,b,c,d,f)},f)})}},TAa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{H6(d),c(!0)}catch(e){}};
d.onerror=function(){try{H6(d),c(!1)}catch(e){}};
d.onabort=function(){try{H6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{H6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},H6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},VAa=function(a){this.g=a;
this.l=new v6},WAa=function(a){var b=I6(a.g,a.wk,"/mail/images/cleardot.gif");
Z5(b);UAa(b.toString(),5E3,(0,g.z)(a.sH,a),3,2E3);a.rf(1)},K6=function(a){var b=a.g.H;
if(null!=b)A6(5),b?(A6(11),J6(a.g,a,!1)):(A6(12),J6(a.g,a,!0));else if(a.te=new w6(a,void 0,void 0,void 0),a.te.ji=a.ur,b=a.g,b=I6(b,b.Pl()?a.Tk:null,a.wr),A6(5),!g.sd||g.oc(10))$5(b,"TYPE","xmlhttp"),x6(a.te,b,!1,a.Tk,!1);else{$5(b,"TYPE","html");var c=a.te;a=!!a.Tk;c.tj=3;c.nh=Z5(b.clone());RAa(c,a)}},L6=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new v6;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},XAa=function(a,b){this.g=a;
this.map=b;this.context=null},YAa=function(a){g.$e.call(this,"statevent",a)},ZAa=function(a,b){g.$e.call(this,"timingevent",a);
this.size=b},$Aa=function(a){g.$e.call(this,"serverreachability",a)},cBa=function(a){aBa(a);
if(3==a.g){var b=a.Bl++,c=a.Cn.clone();g.Em(c,"SID",a.o);g.Em(c,"RID",b);g.Em(c,"TYPE","terminate");M6(a,c);b=new w6(a,a.o,b,void 0);b.tj=2;b.nh=Z5(c.clone());(new window.Image).src=b.nh;b.Xj=(0,g.G)();y6(b)}bBa(a)},dBa=function(a){a.NH(1,0);
a.Cn=I6(a,null,a.tr);N6(a)},aBa=function(a){a.eh&&(a.eh.abort(),a.eh=null);
a.uc&&(a.uc.cancel(),a.uc=null);a.pg&&(g.w.clearTimeout(a.pg),a.pg=null);O6(a);a.Qd&&(a.Qd.cancel(),a.Qd=null);a.gh&&(g.w.clearTimeout(a.gh),a.gh=null)},eBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new XAa(a.hO++,b));2!=a.g&&3!=a.g||N6(a)},N6=function(a){a.Qd||a.gh||(a.gh=F6((0,g.z)(a.SB,a),0),a.lj=0)},gBa=function(a,b){if(1==a.g){if(!b){a.Bl=Math.floor(1E5*Math.random());
var c=a.Bl++,d=new w6(a,"",c,void 0);d.ji=null;var e=P6(a),f=a.Cn.clone();g.Em(f,"RID",c);g.Em(f,"CVER","1");M6(a,f);MAa(d,f,e);a.Qd=d;a.g=2}}else 3==a.g&&(b?fBa(a,b):0==a.l.length||a.Qd||fBa(a))},fBa=function(a,b){if(b)if(6<a.Uh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Bl-1;var d=P6(a)}else c=b.F,d=b.Ii;else c=a.Bl++,d=P6(a);var e=a.Cn.clone();g.Em(e,"SID",a.o);g.Em(e,"RID",c);g.Em(e,"AID",a.Gj);M6(a,e);c=new w6(a,a.o,c,a.lj+1);c.ji=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Qd=c;MAa(c,e,d)},M6=function(a,b){if(a.rd){var c=a.rd.Mx();
c&&g.Kb(c,function(a,c){g.Em(b,c,a)})}},P6=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Uh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Uh?e:f-d;try{g.Kb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},hBa=function(a){a.uc||a.pg||(a.D=1,a.pg=F6((0,g.z)(a.RB,a),0),a.aj=0)},Q6=function(a){if(a.uc||a.pg||3<=a.aj)return!1;
a.D++;a.pg=F6((0,g.z)(a.RB,a),iBa(a,a.aj));a.aj++;return!0},J6=function(a,b,c){a.Ip=c;
a.If=b.xg;a.C||dBa(a)},O6=function(a){null!=a.Wh&&(g.w.clearTimeout(a.Wh),a.Wh=null)},iBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},R6=function(a,b){if(2==b||9==b){var c=null;
a.rd&&(c=null);var d=(0,g.z)(a.fU,a);c||(c=new g.vm("//www.google.com/images/cleardot.gif"),Z5(c));TAa(c.toString(),1E4,d)}else A6(2);jBa(a,b)},jBa=function(a,b){a.g=0;
a.rd&&a.rd.Hw(b);bBa(a);aBa(a)},bBa=function(a){a.g=0;
a.If=-1;if(a.rd)if(0==a.A.length&&0==a.l.length)a.rd.Gq();else{g.Xa(a.A);var b=g.Xa(a.l);a.A.length=0;a.l.length=0;a.rd.Gq(b)}},I6=function(a,b,c){var d=g.Fm(c);
if(""!=d.l)b&&g.xm(d,b+"."+d.l),g.ym(d,d.B);else{var e=window.location;d=jAa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Gk&&g.Kb(a.Gk,function(a,b){g.Em(d,b,a)});
g.Em(d,"VER",a.Uh);M6(a,d);return d},F6=function(a,b){if(!g.Aa(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},A6=function(a){S6.dispatchEvent(new YAa(S6,a))},kBa=function(){},lBa=function(a,b){this.action=a;
this.params=b||{}},T6=function(a,b){g.K.call(this);
this.g=new g.Zt(this.fS,0,this);g.L(this,this.g);this.dd=5E3;this.l=0;if(g.Aa(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Aa(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},U6=function(a,b,c){this.K=a;
this.C=b;this.o=new g.SC;this.l=new T6(this.KU,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.M=c||!1},mBa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Ip,sessionId:a.g.o,arrayId:a.g.Gj}},nBa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&gBa(a.g),cBa(a.g));a.F=0},V6=function(a){return!!a.g&&3==a.g.g},oBa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},W6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Hg(a)||"";b&&(this.port=":"+b);this.domain=g.Gg(a)||"";a=g.Ib;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Ab(a,"10.0")&&(this.l=!1))},X6=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Qg(c+b,{})},Y6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Hb:g.Ea(a.A,d,!0),onError:g.Ea(a.o,e),wd:g.Ea(a.B,e)};c&&(a.ac=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.kE(b,a)},sBa=function(){var a=pBa;
qBa();Z6.push(a);rBa(Z6)},$6=function(a,b){qBa();
var c=Z6,d=tBa(a,String(b));g.Qa(c)?uBa(d):(rBa(c),(0,g.C)(c,function(a){a(d)}))},qBa=function(){Z6||(Z6=g.x("yt.mdx.remote.debug.handlers_")||[],g.va("yt.mdx.remote.debug.handlers_",Z6,void 0))},uBa=function(a){var b=(a7+1)%50;
a7=b;b7[b]=a;c7||(c7=49==b)},rBa=function(a){var b=b7;
if(b[0]){var c=a7,d=c7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.C)(a,function(a){a(e)})}while(d!=c);
b7=Array(50);a7=-1;c7=!1}},tBa=function(a,b){var c=((0,g.G)()-vBa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},d7=function(a){g.EF.call(this);
this.D=a;this.g=[]},wBa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},xBa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Gd)(a.g,function(a){return!!g6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=wBa(a,b[d])||c;return c},yBa=function(a,b){var c=a.g.length;
a.g=(0,g.Gd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},e7=function(a,b,c,d){g.EF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.xa=window.NaN},g7=function(a){d7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;f7(this);this.info("Initializing with "+e6(this.g))},zBa=function(a){if(a.g.length){var b=(0,g.H)(a.g,function(a){return a.id}),c=X6(a.o,"/pairing/get_lounge_token_batch");
Y6(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.sI,a),(0,g.z)(a.rI,a))}},f7=function(a){var b=sAa(xAa());
b=(0,g.Gd)(b,function(a){return!a.uuid});
return xBa(a,b)},h7=function(a,b){zAa((0,g.H)(a.g,qAa));
b&&yAa()},j7=function(a,b){g.EF.call(this);
this.C=b;var c=g.AG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Pa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;i7("Initialized with "+g.xg(this.g))},ABa=function(a,b,c){var d=X6(a.B,"/pairing/get_screen_availability");
Y6(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},k7=function(a,b){a:if(g.Ob(b)!=g.Ob(a.g))var c=!1;
else{c=g.Qb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(i7("Updated online screens: "+g.xg(a.g)),a.g=b,a.P("screenChange"));BBa(a)},l7=function(a){(0,window.isNaN)(a.o)||g.PD(a.o);
a.o=g.ND((0,g.z)(a.tu,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},i7=function(a){$6("OnlineScreenService",a)},CBa=function(a){var b={};
(0,g.C)(a.C(),function(a){a.token?b[a.token]=a.id:this.gc("Requesting availability of screen w/o lounge token.")});
return b},BBa=function(a){a=g.Qb(g.Lb(a.g,function(a){return a}));
g.fb(a);a.length?g.zG("yt-remote-online-screen-ids",a.join(","),60):g.BG("yt-remote-online-screen-ids")},m7=function(a){d7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};DBa(this)},FBa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ne();if(k=(c?h6(k,c):null)||h6(k,b)){k.uuid=b;var l=n7(a,k);ABa(a.l,l,function(a){e(a?l:null)})}else c?EBa(a,c,(0,g.z)(function(a){var f=n7(this,new b6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));ABa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},GBa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},EBa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={ac:{screen_ids:b},method:"POST",context:a,Hb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.kE(X6(a.C,"/pairing/get_lounge_token_batch"),e)},HBa=function(a){a.g=a.o.ne();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+e6(a.g))},DBa=function(a){o7(a);
a.o=new g7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.II,a));HBa(a);a.A=sAa(g.AG("yt-remote-automatic-screen-cache")||[]);o7(a);a.info("Initializing automatic screens: "+e6(a.A));a.l=new j7(a.C,(0,g.z)(a.ne,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.P("onlineScreenChange")},a))},n7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=h6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.zG("yt-remote-automatic-screen-cache",(0,g.H)(a.A,qAa)));o7(a);a.B[b.uuid]=b.id;g.zG("yt-remote-device-id-map",a.B,31536E3);return b},o7=function(a){a.B=g.AG("yt-remote-device-id-map")||{}},p7=function(a,b,c){g.EF.call(this);
this.M=c;this.H=a;this.l=b;this.o=null},q7=function(a,b){$6(a.M,b)},r7=function(a,b){p7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.QU,this);this.B=(0,g.z)(this.PS,this);this.A=g.ND((0,g.z)(function(){IBa(this,null)},this),12E4)},JBa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.xg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){q7(this,"Failed to send message: getMdxSessionStatus.")},a)):q7(a,"Sending yt message without session: "+g.xg(b))},IBa=function(a,b){g.PD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.Oo,a),d=(0,g.z)(a.re,a);a.Xx(b,c,d,5)}}else a.re(Error("Waiting for session status timed out."))},s7=function(a,b,c){p7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.TU,this);this.g=g.y},KBa=function(a){a.g=a.H.aE(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.Oo(a)},a),(0,g.z)(function(a){this.g=g.y;
this.re(a)},a))},LBa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}BAa()&&(b.env_useStageMdx=1);return g.Og(b)},t7=function(a,b){p7.call(this,a,b,"ManualSession");
this.g=g.ND((0,g.z)(this.Hj,this,null),150)},u7=function(a,b,c,d){g.EF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.tR,this)},MBa=function(a,b){return b?g.La(a.o,function(a){return c6(b,a.label)},a):null},v7=function(a){$6("Controller",a)},pBa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},w7=function(a){return a.B||!!a.o.length||!!a.g},x7=function(a,b,c){b!=a.g&&(g.Ye(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.PB,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.Hj(null)):a.P("yt-remote-cast2-session-change",null))},NBa=function(a){var b=a.l.ZD(),c=a.g&&a.g.l;
a=(0,g.H)(b,function(a){c&&c6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=MBa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},TBa=function(a,b,c,d,e,f,k){OBa()?PBa(b,e,f,k)&&(z7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?QBa(a,c):(window.__onGCastApiAvailable=function(b,d){b?QBa(a,c):(A7("Failed to load cast API: "+d),B7(!1),z7(!1),g.BG("yt-remote-cast-available"),g.BG("yt-remote-cast-receiver"),RBa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):EAa():s6("CriOS")?JAa():s6("Android")&&s6("Chrome/")&&window.navigator.presentation?KAa():window.chrome&&window.navigator.presentation&&!s6("Edge")?(t6(),p6(SBa.map(HAa))):q6())):y7("Cannot initialize because not running Chrome")},RBa=function(){y7("dispose");
var a=C7();a&&a.dispose();g.va("yt.mdx.remote.cloudview.instance_",null,void 0);UBa(!1);g.QF(D7);D7.length=0},E7=function(){return!!g.AG("yt-remote-cast-installed")},VBa=function(){var a=g.AG("yt-remote-cast-receiver");
return a?a.friendlyName:null},WBa=function(){y7("clearCurrentReceiver");
g.BG("yt-remote-cast-receiver")},XBa=function(){return E7()?C7()?C7().getCastSession():(A7("getCastSelector: Cast is not initialized."),null):(A7("getCastSelector: Cast API is not installed!"),null)},G7=function(){E7()?C7()?F7()?(y7("Requesting cast selector."),C7().requestSession()):(y7("Wait for cast API to be ready to request the session."),D7.push(g.PF("yt-remote-cast2-api-ready",G7))):A7("requestCastSelector: Cast is not initialized."):A7("requestCastSelector: Cast API is not installed!")},H7=
function(a,b){F7()?C7().setConnectedScreenStatus(a,b):A7("setConnectedScreenStatus called before ready.")},OBa=function(){var a=0<=g.Ib.search(/ (CrMo|Chrome|CriOS)\//);
return g.EJ||a},YBa=function(a,b){C7().init(a,b)},PBa=function(a,b,c,d){var e=!1;
C7()||(a=new u7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.zG("yt-remote-cast-available",a);g.TF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){y7("onReceiverSelected: "+a.friendlyName);
g.zG("yt-remote-cast-receiver",a);g.TF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){y7("onReceiverResumed: "+a.friendlyName);
g.zG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){y7("onSessionChange: "+d6(a));
a||g.BG("yt-remote-cast-receiver");g.TF("yt-remote-cast2-session-change",a)}),g.va("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
y7("cloudview.createSingleton_: "+e);return e},C7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},QBa=function(a,b){B7(!0);
z7(!1);YBa(a,function(a){a?(UBa(!0),g.SF("yt-remote-cast2-api-ready")):(A7("Failed to initialize cast API."),B7(!1),g.BG("yt-remote-cast-available"),g.BG("yt-remote-cast-receiver"),RBa());b(a)})},y7=function(a){$6("cloudview",a)},A7=function(a){$6("cloudview",a)},B7=function(a){y7("setCastInstalled_ "+a);
g.zG("yt-remote-cast-installed",a)},F7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},UBa=function(a){y7("setApiReady_ "+a);
g.va("yt.mdx.remote.cloudview.apiReady_",a,void 0)},z7=function(a){g.va("yt.mdx.remote.cloudview.initializing_",a,void 0)},I7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Lf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},J7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Lf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.G)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},K7=function(a){return a.kb()?((0,g.G)()-a.D)/1E3:0},L7=function(a,b){a.F=b;
a.D=(0,g.G)()},M7=function(a){switch(a.g){case 1:case 1081:return((0,g.G)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},N7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&J7(a)},O7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.ac(a.l);b.hasPrevious=a.Lf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},Q7=function(a,b){g.EF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.iC;this.o=this.l=null;this.H=(0,g.z)(this.QO,this);this.D=(0,g.z)(this.El,this);this.F=(0,g.z)(this.PO,this);this.I=(0,g.z)(this.dP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.qv,this),ZBa(this))):c=3;0!=c&&(b?this.qv(c):g.ND((0,g.z)(function(){this.qv(c)},this),0));
var d=XBa();d&&P7(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},R7=function(a){return new I7(a.A.getPlayerContextData())},ZBa=function(a){(0,g.C)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ea(this.pR,a),this))},a)},$Ba=function(a){(0,g.C)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},S7=function(a,b){50>a.B.Mc()&&g.kC(a.B,b)},U7=function(a,b,c){var d=R7(a);
L7(d,c);-1E3!=d.g&&(d.g=b);T7(a,d)},V7=function(a,b,c){a.A.sendMessage(b,c)},T7=function(a,b){$Ba(a);
a.A.setPlayerContextData(O7(b));ZBa(a)},P7=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.El(null));
a.o=b;a.o&&($6("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.El(a.o.media[0]))},aCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=R7(a);b.contentId!=d.videoId&&$6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;L7(d,a.l.getEstimatedTime());T7(a,d)}else $6("CP","No cast media video. Ignoring state update.")},W7=function(a,b,c){return(0,g.z)(function(a){this.gc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.gc("Retrying "+b+" using MDx browser channel."),V7(this,b,c))},a)},X7=function(a,b,c){g.EF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.M=window.NaN;this.V=[];this.A=this.D=this.o=this.Za=this.g=null;this.ma=a;this.V.push(g.oF(window,"beforeunload",(0,g.z)(this.jI,this)));this.l=[];this.Za=new I7;this.X=b.id;this.g=bCa(this,c);this.g.subscribe("handlerOpened",this.UO,this);this.g.subscribe("handlerClosed",this.RO,this);this.g.subscribe("handlerError",this.SO,this);this.g.subscribe("handlerMessage",this.TO,this);oBa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.FG()&&g.zG("yt-remote-session-video-id",a)},this)},Y7=function(a){$6("conn",a)},bCa=function(a,b){return new U6(X6(a.ma,"/bc"),b)},Z7=function(a,b){a.P("proxyStateChange",b)},cCa=function(a){a.B=g.ND((0,g.z)(function(){Y7("Connecting timeout");
this.C(1)},a),2E4)},$7=function(a){g.PD(a.B);
a.B=window.NaN},a8=function(a){g.PD(a.M);
a.M=window.NaN},dCa=function(a){b8(a);
a.K=g.ND((0,g.z)(function(){c8(this,"getNowPlaying")},a),2E4)},b8=function(a){g.PD(a.K);
a.K=window.NaN},fCa=function(a,b){b&&($7(a),a8(a));
b==(V6(a.g)&&(0,window.isNaN)(a.B))?b&&(Z7(a,1),c8(a,"getSubtitlesTrack")):b?(a.W()&&a.Za.reset(),Z7(a,1),c8(a,"getNowPlaying"),eCa(a)):a.C(1)},gCa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Wb(b.params)?a.Za.l=null:a.Za.l=b.params,a.P("remotePlayerChange"))},hCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;N7(a.Za,c,d);a.P("remoteQueueChange")},jCa=function(a,b){b.params=b.params||{};
hCa(a,b);iCa(a,b);a.P("autoplayDismissed")},iCa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
L7(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?dCa(a):b8(a);
a.P("remotePlayerChange")},kCa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);L7(a.Za,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},lCa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.P("remotePlayerChange")},mCa=function(a,b){a.D=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},nCa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Lf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.P("previousNextChange")},eCa=function(a){g.PD(a.I);
a.I=g.ND((0,g.z)(a.C,a,1),864E5)},c8=function(a,b,c){c?Y7("Sending: action="+b+", params="+g.xg(c)):Y7("Sending: action="+b);
a.g.sendMessage(b,c)},d8=function(a){d7.call(this,"ScreenServiceProxy");
this.cd=a;this.l=[];this.l.push(this.cd.$_s("screenChange",(0,g.z)(this.OU,this)));this.l.push(this.cd.$_s("onlineScreenChange",(0,g.z)(this.QQ,this)))},sCa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.HD("MDX_CONFIG")||b;mAa();l6();e8||(e8=new W6(b?b.loungeApiHost:void 0),BAa()&&(e8.g="/api/loungedev"));f8||(f8=g.x("yt.mdx.remote.deferredProxies_")||[],g.va("yt.mdx.remote.deferredProxies_",f8,void 0));oCa();var c=g8();if(!c){var d=new m7(e8);g.va("yt.mdx.remote.screenService_",d,void 0);c=g8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);TBa(a,d,function(a){a?h8()&&H7(h8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.TF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.va("yt.mdx.remote.initialized_",!0,void 0),i8("Initializing: "+g.xg(b)),j8.push(g.PF("yt-remote-cast2-availability-change",function(){g.TF("yt-remote-receiver-availability-change")})),j8.push(g.PF("yt-remote-cast2-receiver-selected",function(){k8(null);
g.TF("yt-remote-auto-connect","cast-selector-receiver")})),j8.push(g.PF("yt-remote-cast2-receiver-resumed",function(){g.TF("yt-remote-receiver-resumed","cast-selector-receiver")})),j8.push(g.PF("yt-remote-cast2-session-change",pCa)),j8.push(g.PF("yt-remote-connection-change",function(a){a?H7(h8(),"YouTube TV"):l8()||(H7(null,null),WBa())})),a=m8(),b.isAuto&&(a.id+="#dial"),g.FE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),i8(" -- with channel params: "+
g.xg(a)),qCa(a),c.start(),h8()||rCa())},uCa=function(){var a=tCa();
E7()&&g.AG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},tCa=function(){var a=g8().cd.$_gos();
var b=n8();b&&o8()&&(g6(a,b)||a.push(b));return tAa(a)},p8=function(){var a=vCa();
!a&&E7()&&VBa()&&(a={key:"cast-selector-receiver",name:VBa()});return a},vCa=function(){var a=tCa(),b=n8();
b||(b=l8());return g.La(a,function(a){return b&&c6(b,a.key)?!0:!1})},n8=function(){var a=h8();
if(!a)return null;var b=g8().ne();return h6(b,a)},pCa=function(a){i8("remote.onCastSessionChange_: "+d6(a));
if(a){var b=n8();b&&b.id==a.id?H7(b.id,"YouTube TV"):(b&&q8(),r8(a,1))}else o8()&&q8()},q8=function(){F7()?C7().stopSession():A7("stopSession called before API ready.");
var a=o8();a&&(a.disconnect(1),s8(null))},t8=function(){var a=o8();
return!!a&&3!=a.getProxyState()},i8=function(a){$6("remote",a)},g8=function(){if(!u8){var a=g.x("yt.mdx.remote.screenService_");
u8=a?new d8(a):null}return u8},h8=function(){return g.x("yt.mdx.remote.currentScreenId_")},wCa=function(a){g.va("yt.mdx.remote.currentScreenId_",a,void 0)},xCa=function(){return g.x("yt.mdx.remote.connectData_")},k8=function(a){g.va("yt.mdx.remote.connectData_",a,void 0)},o8=function(){return g.x("yt.mdx.remote.connection_")},s8=function(a){var b=o8();
k8(null);a||wCa("");g.va("yt.mdx.remote.connection_",a,void 0);f8&&((0,g.C)(f8,function(b){b(a)}),f8.length=0);
b&&!a?g.TF("yt-remote-connection-change",!1):!b&&a&&g.TF("yt-remote-connection-change",!0)},l8=function(){var a=g.FG();
if(!a)return null;var b=g8().ne();return h6(b,a)},r8=function(a,b){n8()&&n8();
wCa(a.id);var c=new X7(e8,a,m8());c.connect(b,xCa());c.subscribe("beforeDisconnect",function(a){g.TF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){o8()&&s8(null)});
s8(c)},rCa=function(){var a=l8();
a?(i8("Resume connection to: "+d6(a)),r8(a,0)):(m6(),WBa(),i8("Skipping connecting because no session screen found."))},oCa=function(){var a=m8();
if(g.Wb(a)){a=k6();var b=g.AG("yt-remote-session-name")||"",c=g.AG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.va("yt.mdx.remote.channelParams_",a,void 0)}},m8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},qCa=function(a){a?(g.zG("yt-remote-session-app",a.app),g.zG("yt-remote-session-name",a.name)):(g.BG("yt-remote-session-app"),g.BG("yt-remote-session-name"));
g.va("yt.mdx.remote.channelParams_",a,void 0)},v8=function(a,b,c){g.K.call(this);
this.F=a;this.l=b;this.o=new g.BF(this);g.L(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.iQ);this.o.O(b,"captionschanged",this.OO);this.o.O(b,"captionssettingschanged",this.iD);this.o.O(b,"videoplayerreset",this.Qo);this.o.O(b,"mdxautoplaycancel",this.rH);this.V=this.o.O(b,"onVolumeChange",this.zB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.MB,this);c.subscribe("remotePlayerChange",this.Hl,this);c.subscribe("remoteQueueChange",this.Qo,this);c.subscribe("autoplayUpNext",this.iB,
this);c.subscribe("previousNextChange",this.JB,this);c.subscribe("nowAutoplaying",this.BB,this);c.subscribe("autoplayDismissed",this.hB,this);this.suggestion=null;this.H=new g.GO(64);this.A=new g.Zt(this.eD,500,this);g.L(this,this.A);this.B=new g.Zt(this.fD,1E3,this);g.L(this,this.B);this.K=new u6(this.rU,0,this);g.L(this,this.K);this.C={};this.M=new g.Zt(this.LD,1E3,this);g.L(this,this.M);this.I=new g.Ok(this.UM,1E3,this);g.L(this,this.I);this.N=g.y;this.iD();this.Qo();this.Hl()},w8=function(a,b){var c=
a.F,d=a.l.ea().lengthSeconds;
c.H=b||0;c.g.P("progresssync",b,d)},yCa=function(a){w8(a,0);
a.A.stop();x8(a,new g.GO(64))},z8=function(a,b){if(y8(a)&&!a.D){var c=null;
b&&(c={style:a.l.Bi()},g.cc(c,b));a.g.WC(a.l.ea(1).videoId,c);a.C=R7(a.g).l}},A8=function(a,b){var c=a.l.Wf();
if(c){var d=c.je();var e=c.listId.toString()}var f=a.l.ea(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.Dj;var m=R7(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};N7(m,k,l);g.t(b)&&(L7(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);V7(c,"setPlaylist",q);e||T7(c,m);x8(a,new g.GO(1))},zCa=function(a,b){if(b){var c=a.l.zc("captions","tracklist",{Ty:1});
c&&c.length?(a.l.Jd("captions","track",b),a.D=!1):(a.l.sl("captions"),a.D=!0)}else a.l.Jd("captions","track",{})},y8=function(a){return R7(a.g).videoId==a.l.ea(1).videoId},x8=function(a,b){a.B.stop();
var c=a.H;if(!g.OO(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.YU(a.l,d);a.H=b;ACa(a.F,c,b)}},B8=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",J:[{G:"div",L:"ytp-remote-display-status",J:[{G:"div",L:"ytp-remote-display-status-icon",J:[g.Rna()]},{G:"div",L:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.l=new g.IV(this,250);g.L(this,this.l);this.o=a;this.O(a,"presentingplayerstatechange",this.A);BCa(this,g.VU(a))},BCa=function(a,b){if(3==a.o.Ta()){var c={RECEIVER_NAME:a.o.zc("remote","currentReceiver").name};
c=g.X(b,128)?g.V("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.X(b,4)?g.V("YTP_MDX_STATUS_PLAYING_2",c):g.V("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},C8=function(a,b){g.KZ.call(this,g.V("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.F={};this.O(a,"onMdxReceiversChange",this.I);this.O(a,"presentingplayerstatechange",this.I);this.I()},D8=function(a){g.vV.call(this,a);
g.HG({YTP_MDX_CAST_SELECTOR:"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c",YTP_MDX_MY_COMPUTER:"\u042d\u0442\u043e\u0442 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440",YTP_MDX_PLAYER_ERROR:"\u0412\u0438\u0434\u0435\u043e \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e \u0434\u043b\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u044f.",YTP_MDX_STATUS_CONNECTED_2:'\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435 \u043a \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0443 "$RECEIVER_NAME"',
YTP_MDX_STATUS_ERROR_2:'\u041e\u0448\u0438\u0431\u043a\u0430 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',YTP_MDX_STATUS_PLAYING_2:'\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',YTP_MDX_TITLE:"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430"});
this.o={key:f6(),name:g.V("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.GO(64);this.H=0;if(!g.qM(g.Y(this.g))){a=this.g;var b=g.YH(a);b&&(b=b.wo())&&(b=new C8(a,b),g.L(this,b));b=new B8(a);g.L(this,b);g.pV(a,b.element,4)}},ACa=function(a,b,c){a.D=c;
a.g.P("presentingplayerstatechange",new g.UO(c,b))},E8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)q8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ea(1),e=d.videoId;if(c||e){var f=a.g.Wf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.kc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Dj,index:Math.max(a.g.Rz(),0),currentTime:0==f?void 0:f}}else c=null;i8("Connecting to: "+g.xg(b));"cast-selector-receiver"==b.key?(k8(c||null),F7()?C7().setLaunchParams(c||null):A7("setLaunchParams called before ready.")):!c&&
t8()&&h8()==b.key?g.TF("yt-remote-connection-change",!0):(q8(),k8(c||null),c=g8().ne(),(c=h6(c,b.key))&&r8(c,1))}},QAa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},E6={"'":"\\'"},CCa={},pAa={fW:"atp",C0:"ska",R_:"que",c_:"mus",y0:"sus"};
a6.prototype.kn=function(){var a=new a6({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var n6,j6="",r6=o6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",IAa=o6("loadCastFramework")||o6("loadCastApplicationFramework"),SBa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(u6,g.K);g.h=u6.prototype;g.h.fI=function(a){this.A=arguments;this.g=!1;this.xa?this.o=(0,g.G)()+this.dd:this.xa=g.rg(this.B,this.dd)};
g.h.stop=function(){this.xa&&(g.sg(this.xa),this.xa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.U=function(){this.stop();u6.Z.U.call(this)};
g.h.gI=function(){this.o?(this.xa=g.rg(this.B,this.o-(0,g.G)()),this.o=null):(this.xa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};v6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
v6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=w6.prototype;g.h.ji=null;g.h.wf=!1;g.h.sk=null;g.h.gv=null;g.h.Xj=null;g.h.tj=null;g.h.nh=null;g.h.Fh=null;g.h.Ii=null;g.h.Qc=null;g.h.Wl=0;g.h.xf=null;g.h.Jp=null;g.h.oh=null;g.h.Uk=-1;g.h.EC=!0;g.h.Sh=!1;g.h.xr=0;g.h.bp=null;var OAa={},z6={};g.h=w6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.kT=function(a){a=a.target;var b=this.bp;b&&3==g.mx(a)?b.rj():this.TD(a)};
g.h.TD=function(a){try{if(a==this.Qc)a:{var b=g.mx(this.Qc),c=this.Qc.l,d=this.Qc.getStatus();if(g.sd&&!g.oc(10)||g.ud&&!g.nc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.bf&&!g.qx(this.Qc))break a;this.Sh||4!=b||7==c||(8==c||0>=d?this.g.rf(3):this.g.rf(2));G6(this);var e=this.Qc.getStatus();this.Uk=e;var f=g.qx(this.Qc);(this.wf=200==e)?(4==b&&C6(this),this.C?(PAa(this,b,f),g.bf&&this.wf&&3==b&&(this.A.R(this.l,"tick",this.dT),this.l.start())):B6(this,f),this.wf&&!this.Sh&&(4==b?this.g.No(this):
(this.wf=!1,y6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.oh=3,A6(13)):(this.oh=0,A6(14)),C6(this),D6(this))}}catch(k){this.Qc&&g.qx(this.Qc)}finally{}};
g.h.dT=function(){var a=g.mx(this.Qc),b=g.qx(this.Qc);this.Wl<b.length&&(G6(this),PAa(this,a,b),this.wf&&4!=a&&y6(this))};
g.h.oS=function(a){F6((0,g.z)(this.nS,this,a),0)};
g.h.nS=function(a){this.Sh||(G6(this),B6(this,a),y6(this))};
g.h.UB=function(a){F6((0,g.z)(this.mS,this,a),0)};
g.h.mS=function(a){this.Sh||(C6(this),this.wf=a,this.g.No(this),this.g.rf(4))};
g.h.cancel=function(){this.Sh=!0;C6(this)};
g.h.FS=function(){this.sk=null;var a=(0,g.G)();0<=a-this.gv?(2!=this.tj&&this.g.rf(3),C6(this),this.oh=2,A6(18),D6(this)):SAa(this,this.gv-a)};g.h=VAa.prototype;g.h.ur=null;g.h.te=null;g.h.cp=!1;g.h.hy=null;g.h.zn=null;g.h.vr=null;g.h.wr=null;g.h.Le=null;g.h.xg=-1;g.h.Tk=null;g.h.wk=null;g.h.connect=function(a){this.wr=a;a=I6(this.g,null,this.wr);A6(3);this.hy=(0,g.G)();var b=this.g.F;null!=b?(this.Tk=b[0],(this.wk=b[1])?(this.Le=1,WAa(this)):(this.Le=2,K6(this))):($5(a,"MODE","init"),this.te=new w6(this,void 0,void 0,void 0),this.te.ji=this.ur,x6(this.te,a,!1,null,!0),this.Le=0)};
g.h.sH=function(a){if(a)this.Le=2,K6(this);else{A6(4);var b=this.g;b.If=b.eh.xg;R6(b,9)}a&&this.rf(2)};
g.h.Rq=function(a){return this.g.Rq(a)};
g.h.abort=function(){this.te&&(this.te.cancel(),this.te=null);this.xg=-1};
g.h.gy=function(){return!1};
g.h.NB=function(a,b){this.xg=a.Uk;if(0==this.Le)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.If=this.xg;R6(c,2);return}this.Tk=c[0];this.wk=c[1]}else c=this.g,c.If=this.xg,R6(c,2);else if(2==this.Le)if(this.cp)A6(7),this.vr=(0,g.G)();else if("11111"==b){if(A6(6),this.cp=!0,this.zn=(0,g.G)(),c=this.zn-this.hy,!g.sd||g.oc(10)||500>c)this.xg=200,this.te.cancel(),A6(12),J6(this.g,this,!0)}else A6(8),this.zn=this.vr=(0,g.G)(),this.cp=!1};
g.h.No=function(){this.xg=this.te.Uk;if(this.te.wf)0==this.Le?this.wk?(this.Le=1,WAa(this)):(this.Le=2,K6(this)):2==this.Le&&((!g.sd||g.oc(10)?!this.cp:200>this.vr-this.zn)?(A6(11),J6(this.g,this,!1)):(A6(12),J6(this.g,this,!0)));else{0==this.Le?A6(9):2==this.Le&&A6(10);var a=this.g;a.If=this.xg;R6(a,2)}};
g.h.Pl=function(){return this.g.Pl()};
g.h.isActive=function(){return this.g.isActive()};
g.h.rf=function(a){this.g.rf(a)};g.h=L6.prototype;g.h.Gk=null;g.h.Qd=null;g.h.uc=null;g.h.tr=null;g.h.Cn=null;g.h.yw=null;g.h.Rn=null;g.h.Bl=0;g.h.hO=0;g.h.rd=null;g.h.gh=null;g.h.pg=null;g.h.Wh=null;g.h.eh=null;g.h.Ip=null;g.h.Gj=-1;g.h.fz=-1;g.h.If=-1;g.h.lj=0;g.h.aj=0;g.h.Uh=8;var S6=new g.Cf;g.A(YAa,g.$e);g.A(ZAa,g.$e);g.A($Aa,g.$e);g.h=L6.prototype;g.h.connect=function(a,b,c,d,e){A6(0);this.tr=b;this.Gk=c||{};d&&g.t(e)&&(this.Gk.OSID=d,this.Gk.OAID=e);this.C?(F6((0,g.z)(this.Uw,this,a),100),dBa(this)):this.Uw(a)};
g.h.Uw=function(a){this.eh=new VAa(this);this.eh.ur=null;this.eh.l=this.B;this.eh.connect(a)};
g.h.gy=function(){return 0==this.g};
g.h.SB=function(a){this.gh=null;gBa(this,a)};
g.h.RB=function(){this.pg=null;this.uc=new w6(this,this.o,"rpc",this.D);this.uc.ji=null;this.uc.xr=0;var a=this.yw.clone();g.Em(a,"RID","rpc");g.Em(a,"SID",this.o);g.Em(a,"CI",this.Ip?"0":"1");g.Em(a,"AID",this.Gj);M6(this,a);if(!g.sd||g.oc(10))g.Em(a,"TYPE","xmlhttp"),x6(this.uc,a,!0,this.Rn,!1);else{g.Em(a,"TYPE","html");var b=this.uc,c=!!this.Rn;b.tj=3;b.nh=Z5(a.clone());RAa(b,c)}};
g.h.NB=function(a,b){if(0!=this.g&&(this.uc==a||this.Qd==a))if(this.If=a.Uk,this.Qd==a&&3==this.g)if(7<this.Uh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.ya(c)&&3==c.length)if(0==c[0])a:{if(!this.pg){if(this.uc)if(this.uc.Xj+3E3<this.Qd.Xj)O6(this),this.uc.cancel(),this.uc=null;else break a;Q6(this);A6(19)}}else this.fz=c[1],0<this.fz-this.Gj&&37500>c[2]&&this.Ip&&0==this.aj&&!this.Wh&&(this.Wh=F6((0,g.z)(this.JO,this),6E3));else R6(this,11)}else b!=CCa.mX.g&&R6(this,11);else if(this.uc==a&&
O6(this),!g.D(b)){c=this.B.parse(b);g.ya(c);for(var d=0;d<c.length;d++){var e=c[d];this.Gj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Rn=e[2],e=e[3],null!=e?this.Uh=e:this.Uh=6,this.g=3,this.rd&&this.rd.Jw(),this.yw=I6(this,this.Pl()?this.Rn:null,this.tr),hBa(this)):"stop"==e[0]&&R6(this,7):3==this.g&&("stop"==e[0]?R6(this,7):"noop"!=e[0]&&this.rd&&this.rd.Iw(e),this.aj=0)}}};
g.h.JO=function(){null!=this.Wh&&(this.Wh=null,this.uc.cancel(),this.uc=null,Q6(this),A6(20))};
g.h.No=function(a){if(this.uc==a){O6(this);this.uc=null;var b=2}else if(this.Qd==a)this.Qd=null,b=1;else return;this.If=a.Uk;if(0!=this.g)if(a.wf)1==b?(b=(0,g.G)()-a.Xj,S6.dispatchEvent(new ZAa(S6,a.Ii?a.Ii.length:0,b,this.lj)),N6(this),this.A.length=0):hBa(this);else{var c=a.oh,d;if(!(d=3==c||7==c||0==c&&0<this.If)){if(d=1==b)this.Qd||this.gh||1==this.g||2<=this.lj?d=!1:(this.gh=F6((0,g.z)(this.SB,this,a),iBa(this,this.lj)),this.lj++,d=!0);d=!(d||2==b&&Q6(this))}if(d)switch(c){case 1:R6(this,5);
break;case 4:R6(this,10);break;case 3:R6(this,6);break;case 7:R6(this,12);break;default:R6(this,2)}}};
g.h.NH=function(a){if(!g.Pa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.fU=function(a){a?A6(2):(A6(1),jBa(this,8))};
g.h.Rq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.gx;a.F=!1;return a};
g.h.isActive=function(){return!!this.rd&&this.rd.isActive(this)};
g.h.rf=function(a){S6.dispatchEvent(new $Aa(S6,a))};
g.h.Pl=function(){return!(!g.sd||g.oc(10))};
g.h=kBa.prototype;g.h.Jw=function(){};
g.h.Iw=function(){};
g.h.Hw=function(){};
g.h.Gq=function(){};
g.h.Mx=function(){return{}};
g.h.isActive=function(){return!0};g.A(T6,g.K);g.h=T6.prototype;g.h.fS=function(){this.dd=Math.min(3E5,2*this.dd);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.dd+15E3*Math.random();g.$t(this.g,a);this.l=(0,g.G)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.dd=5E3};g.A(U6,kBa);g.h=U6.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Ld=function(a){return this.o.Ld(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.Ye(this.o),nBa(this),g.Ye(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new L6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.g;e&&(e.rd=null);d.rd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Gj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.cc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):V6(this)&&eBa(this.g,c)};
g.h.Jw=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)eBa(this.g,a[b])}this.P("handlerOpened")};
g.h.Hw=function(a){var b=2==a&&401==this.g.If;4==a||b||this.l.start();this.P("handlerError",a)};
g.h.Gq=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Mx=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.cc(a,this.B);return a};
g.h.Iw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),cBa(this.g)):this.P("handlerMessage",new lBa(a[0],a[1]))};
g.h.KU=function(){this.l.isActive();var a=this.g,b=0;a.uc&&b++;a.Qd&&b++;0!=b||this.connect(this.B,this.A)};W6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
W6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
W6.prototype.B=function(a){a(Error("request timed out"))};var vBa=(0,g.G)(),Z6=null,b7=Array(50),a7=-1,c7=!1;g.A(d7,g.EF);d7.prototype.ne=function(){return this.g};
d7.prototype.contains=function(a){return!!g6(this.g,a)};
d7.prototype.get=function(a){return a?h6(this.g,a):null};
d7.prototype.info=function(a){$6(this.D,a)};g.A(e7,g.EF);var DCa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=e7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.xa)&&this.YD()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.xa)||(g.PD(this.xa),this.xa=window.NaN)};
g.h.U=function(){this.stop();e7.Z.U.call(this)};
g.h.YD=function(){this.xa=window.NaN;this.g=g.kE(X6(this.C,"/pairing/get_screen"),{method:"POST",ac:{pairing_code:this.B},timeout:5E3,Hb:(0,g.z)(this.MU,this),onError:(0,g.z)(this.LU,this),wd:(0,g.z)(this.NU,this)})};
g.h.MU=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new b6(c))};
g.h.LU=function(a){this.g=null;a.status&&404==a.status?this.l>=DCa.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=DCa[this.l],this.xa=g.ND((0,g.z)(this.YD,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.NU=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.A(g7,d7);g.h=g7.prototype;g.h.start=function(){f7(this)&&this.P("screenChange");!g.AG("yt-remote-lounge-token-expiration")&&zBa(this);g.PD(this.l);this.l=g.ND((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){f7(this);wBa(this,a);h7(this,!1);this.P("screenChange");b(a);a.token||zBa(this)};
g.h.remove=function(a,b){var c=f7(this);yBa(this,a)&&(h7(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.Ep=function(a,b,c,d){var e=f7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,h7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.U=function(){g.PD(this.l);g7.Z.U.call(this)};
g.h.sI=function(a){f7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}h7(this,!b);b&&$6(this.D,"Missed "+b+" lounge tokens.")};
g.h.rI=function(a){$6(this.D,"Requesting lounge tokens failed: "+a)};g.A(j7,g.EF);g.h=j7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.AG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?l7(this):(this.A=(0,g.G)()+3E5,g.zG("yt-remote-fast-check-period",this.A),this.tu())};
g.h.isEmpty=function(){return g.Wb(this.g)};
g.h.update=function(){i7("Updating availability on schedule.");var a=this.C(),b=g.Lb(this.g,function(b,d){return b&&!!h6(a,d)},this);
k7(this,b)};
g.h.U=function(){g.PD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);j7.Z.U.call(this)};
g.h.tu=function(){g.PD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=CBa(this);if(g.Ob(a)){var b=X6(this.B,"/pairing/get_screen_availability");this.l=Y6(this.B,b,{lounge_token:g.Qb(a).join(",")},(0,g.z)(this.NR,this,a),(0,g.z)(this.MR,this))}else k7(this,{}),l7(this)};
g.h.NR=function(a,b){this.l=null;var c=g.Qb(CBa(this));if(g.gb(c,g.Qb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;k7(this,d);l7(this)}else this.gc("Changing Screen set during request."),this.tu()};
g.h.MR=function(a){this.gc("Screen availability failed: "+a);this.l=null;l7(this)};
g.h.gc=function(a){$6("OnlineScreenService",a)};g.A(m7,d7);g.h=m7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Ep=function(a,b,c,d){this.o.contains(a)?this.o.Ep(a,b,c,d):(a="Updating name of unknown screen: "+a.name,$6(this.D,a),d(Error(a)))};
g.h.ne=function(a){return a?this.g:g.Wa(this.g,(0,g.Gd)(this.A,function(a){return!this.contains(a)},this))};
g.h.ZD=function(){return(0,g.Gd)(this.ne(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.aE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new e7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.Ye(f);d(n7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ye(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.PU=function(a,b,c,d){g.kE(X6(this.C,"/pairing/get_screen"),{method:"POST",ac:{pairing_code:a},timeout:5E3,Hb:(0,g.z)(function(a,d){var e=new b6(d.screen||{});if(!e.name||GBa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);GBa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(n7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
wd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.Ye(this.o);g.Ye(this.l);m7.Z.U.call(this)};
g.h.II=function(){HBa(this);this.P("screenChange");this.l.update()};
m7.prototype.dispose=m7.prototype.dispose;g.A(p7,g.EF);g.h=p7.prototype;g.h.Oo=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.re=function(a){this.ha()||(a&&q7(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){$6(this.M,a)};
g.h.cE=function(){return null};
g.h.Bu=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){q7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Bu("");p7.Z.U.call(this)};g.A(r7,p7);g.h=r7.prototype;g.h.Au=function(a){if(this.g){if(this.g==a)return;q7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);JBa(this)};
g.h.Hj=function(a){this.info("launchWithParams no-op for Cast: "+g.xg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.re()},this),(0,g.z)(function(){this.re(Error("Failed to stop receiver app."))},this)):this.re(Error("Stopping cast device witout session."))};
g.h.Bu=g.y;g.h.U=function(){this.info("disposeInternal");g.PD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;r7.Z.U.call(this)};
g.h.PS=function(a,b){if(!this.ha())if(b){var c=g.Xw(b);if(g.Ba(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.xg(c));switch(d){case "mdxSessionStatus":IBa(this,c.screenId);break;default:q7(this,"Unknown youtube message: "+d)}}else q7(this,"Unable to parse message.")}else q7(this,"No data in message.")};
g.h.Xx=function(a,b,c,d){FBa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(q7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.ND((0,g.z)(this.Xx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.cE=function(){return this.g};
g.h.QU=function(a){this.ha()||a||(q7(this,"Cast session died."),this.re())};g.A(s7,p7);g.h=s7.prototype;g.h.Au=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Hj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.PD(this.C);this.A?this.A.stop((0,g.z)(this.re,this,null),(0,g.z)(this.re,this,"Failed to stop DIAL device.")):this.re()};
g.h.U=function(){this.g();this.g=g.y;g.PD(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;s7.Z.U.call(this)};
g.h.TU=function(a){this.ha()||a||(q7(this,"DIAL session died."),this.g(),this.g=g.y,this.re())};
g.h.ks=function(a){this.I=f6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,LBa(this));a(b);KBa(this)}else this.D=(0,g.z)(function(){g.PD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,LBa(this));a(b);KBa(this)},this),this.C=g.ND((0,g.z)(function(){this.D()},this),100)};
g.h.YJ=function(a,b,c){FBa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.Oo(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.ks(b,c)},this),(0,g.z)(function(a){q7(this,"Failed to get DIAL screen: "+a);
this.ks(b,c)},this))};g.A(t7,p7);t7.prototype.stop=function(){this.re()};
t7.prototype.Au=g.y;t7.prototype.Hj=function(){g.PD(this.g);this.g=window.NaN;var a=h6(this.H.ne(),this.l.label);a?this.Oo(a):this.re(Error("No such screen"))};
t7.prototype.U=function(){g.PD(this.g);this.g=window.NaN;t7.Z.U.call(this)};g.A(u7,g.EF);g.h=u7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.OB,this),(0,g.z)(this.xR,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.uP,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),sBa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.bE,this)),this.o=NBa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.gc("Failed to set initial custom receivers: "+g.xg(a))},this)),this.P("yt-remote-cast2-availability-change",w7(this)),b(!0))},this),(0,g.z)(function(a){this.gc("Failed to initialize API: "+g.xg(a));
b(!1)},this))};
g.h.LT=function(a,b){v7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)v7("Unsetting old screen status: "+this.g.l.friendlyName),x7(this,null)}if(a&&b){if(!this.g){c=h6(this.l.ne(),a);if(!c){v7("setConnectedScreenStatus: Unknown screen.");return}var d=MBa(this,c);d||(v7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.gc("Failed to set initial custom receivers: "+g.xg(a))},this)));
v7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);x7(this,new t7(this.l,d),!0)}this.g.Bu(b)}else v7("setConnectedScreenStatus: no screen.")};
g.h.NT=function(a){this.ha()?this.gc("Setting connection data on disposed cast v2"):this.g?this.g.Hj(a):this.gc("Setting connection data without a session")};
g.h.SU=function(){this.ha()?this.gc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),x7(this,null)):v7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.OB,this),(0,g.z)(this.SR,this))};
g.h.U=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.bE,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ua(g.x("yt.mdx.remote.debug.handlers_")||[],pBa);g.Ye(this.g);u7.Z.U.call(this)};
g.h.gc=function(a){$6("Controller",a)};
g.h.PB=function(a,b){this.g==a&&(b||x7(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.tR=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),v7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)v7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{v7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:x7(this,
new t7(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:x7(this,new s7(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:x7(this,new r7(this.l,a));break;default:this.gc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.gc("Stopping receiver w/o session: "+a.friendlyName)}else this.gc("onReceiverAction_ called without receiver.")};
g.h.uP=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.gc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.gc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return v7("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.gc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);x7(this,new s7(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.YJ,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.ks,b))};
g.h.OB=function(a){if(!this.ha()){v7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)v7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),x7(this,new r7(this.l,b),!0);else{this.gc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=h6(this.l.ne(),c.label);
d&&c6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(v7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ye(this.g),this.g=new r7(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.PB,this,this.g)),this.g.Hj(null));this.g.Au(a)}}};
g.h.RU=function(){return this.g?this.g.cE():null};
g.h.SR=function(a){this.ha()||(this.gc("Failed to estabilish a session: "+g.xg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&x7(this,null))};
g.h.xR=function(a){v7("Receiver availability updated: "+a);if(!this.ha()){var b=w7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;w7(this)!=b&&this.P("yt-remote-cast2-availability-change",w7(this))}};
g.h.bE=function(){this.ha()||(this.o=NBa(this),v7("Updating custom receivers: "+g.xg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.gc("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",w7(this)))};
u7.prototype.setLaunchParams=u7.prototype.NT;u7.prototype.setConnectedScreenStatus=u7.prototype.LT;u7.prototype.stopSession=u7.prototype.SU;u7.prototype.getCastSession=u7.prototype.RU;u7.prototype.requestSession=u7.prototype.requestSession;u7.prototype.init=u7.prototype.init;u7.prototype.dispose=u7.prototype.dispose;var D7=[];g.h=I7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";J7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Lf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+K7(this):this.H};
g.h.clone=function(){return new I7(O7(this))};g.A(Q7,g.EF);g.h=Q7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,W7(this,"play")):V7(this,"play"),U7(this,1,M7(R7(this))),this.P("remotePlayerChange")):S7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,W7(this,"pause")):V7(this,"pause"),U7(this,2,M7(R7(this))),this.P("remotePlayerChange")):S7(this,this.pause)};
g.h.XD=function(a){if(1==this.g){if(this.l){var b=R7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,W7(this,"seekTo",{newTime:a}))}else V7(this,"seekTo",{newTime:a});U7(this,3,a);this.P("remotePlayerChange")}else S7(this,g.Ea(this.XD,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,W7(this,"stopVideo")):V7(this,"stopVideo");var a=R7(this);a.index=-1;a.videoId="";J7(a);T7(this,a);this.P("remotePlayerChange")}else S7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=R7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){$6("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.gc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){$6("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.gc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);V7(this,"setVolume",e)}c.muted=b;c.volume=a;T7(this,c)}else S7(this,g.Ea(this.setVolume,a,b))};
g.h.WC=function(a,b){if(1==this.g){var c=R7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.xg(b.style),g.cc(d,c.l));V7(this,"setSubtitlesTrack",d);T7(this,c)}else S7(this,g.Ea(this.WC,a,b))};
g.h.ov=function(a,b){if(1==this.g){V7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Ob.id});var c=R7(this);c.audioTrackId=b.Ob.id;T7(this,c)}else S7(this,g.Ea(this.ov,a,b))};
g.h.WD=function(a,b){if(1==this.g){if(a&&b){var c=R7(this);N7(c,a,b);T7(this,c)}V7(this,"previous")}else S7(this,g.Ea(this.WD,a,b))};
g.h.VD=function(a,b){if(1==this.g){if(a&&b){var c=R7(this);N7(c,a,b);T7(this,c)}V7(this,"next")}else S7(this,g.Ea(this.VD,a,b))};
g.h.qx=function(){1==this.g?V7(this,"dismissAutoplay"):S7(this,this.qx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}Q7.Z.dispose.call(this)};
g.h.U=function(){$Ba(this);this.A=null;this.B.clear();P7(this,null);Q7.Z.U.call(this)};
g.h.qv=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.lC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.pR=function(a,b){this.P(a,b)};
g.h.QO=function(a){if(!a)this.El(null),P7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=R7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)$6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,T7(this,b)}};
g.h.El=function(a){$6("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),aCa(this),this.P("remotePlayerChange")};
g.h.PO=function(a){a?(aCa(this),this.P("remotePlayerChange")):this.El(null)};
g.h.dP=function(){var a=XBa();a&&P7(this,a)};
g.h.gc=function(a){$6("CP",a)};g.A(X7,g.EF);g.h=X7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;L7(this.Za,m);this.A="UNSUPPORTED";Y7("Connecting with setPlaylist and params: "+g.xg(l));this.g.connect({method:"setPlaylist",params:g.xg(l)},a,wAa())}else Y7("Connecting without params"),
this.g.connect({},a,wAa());cCa(this)};
g.h.dispose=function(){this.ha()||(this.P("beforeDispose"),Z7(this,3));X7.Z.dispose.call(this)};
g.h.U=function(){$7(this);b8(this);a8(this);g.PD(this.H);this.H=window.NaN;g.PD(this.I);this.I=window.NaN;this.o=null;g.pF(this.V);this.V.length=0;this.g.dispose();X7.Z.U.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.jI=function(){this.C(2)};
g.h.UO=function(){Y7("Channel opened");this.N&&(this.N=!1,a8(this),this.M=g.ND((0,g.z)(function(){Y7("Timing out waiting for a screen.");this.C(1)},this),15E3));
AAa(mBa(this.g),this.X)};
g.h.RO=function(){Y7("Channel closed");(0,window.isNaN)(this.B)?m6(!0):m6();this.dispose()};
g.h.SO=function(a){m6();(0,window.isNaN)(this.F())?(Y7("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,Y7("Channel error: "+a+" with reconnection in "+this.F()+" ms"),Z7(this,2))};
g.h.TO=function(a){a.params?Y7("Received: action="+a.action+", params="+g.xg(a.params)):Y7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Xw(a.params.devices);this.l=(0,g.H)(a,function(a){return new a6(a)});
a=!!g.La(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
fCa(this,a);break;case "loungeScreenDisconnected":g.Va(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
fCa(this,!1);break;case "remoteConnected":var b=new a6(g.Xw(a.params.device));g.La(this.l,function(a){return b?a.id==b.id:!1})||g.Sa(this.l,b);
break;case "remoteDisconnected":b=new a6(g.Xw(a.params.device));g.Va(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":hCa(this,a);break;case "nowPlaying":jCa(this,a);break;case "onStateChange":iCa(this,a);break;case "onAdStateChange":kCa(this,a);break;case "onVolumeChanged":lCa(this,a);break;case "onSubtitlesTrackChanged":gCa(this,a);break;case "nowAutoplaying":mCa(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.P("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":nCa(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:Y7("Unrecognized action: "+a.action)}};
g.h.wT=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&c8(this,"getNowPlaying")}};
X7.prototype.subscribe=X7.prototype.subscribe;X7.prototype.unsubscribeByKey=X7.prototype.Ld;X7.prototype.da=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?V6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
X7.prototype.getProxyState=X7.prototype.da;X7.prototype.C=function(a){Y7("Disconnecting with "+a);$7(this);this.P("beforeDisconnect",a);1==a&&m6();nBa(this.g,a);this.dispose()};
X7.prototype.disconnect=X7.prototype.C;X7.prototype.ca=function(){var a=this.Za;this.o&&(a=this.Za.clone(),N7(a,this.o,a.index));return O7(a)};
X7.prototype.getPlayerContextData=X7.prototype.ca;
X7.prototype.ka=function(a){var b=new I7(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.PD(this.H),this.H=g.ND((0,g.z)(this.wT,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&M7(this.Za)==M7(b)&&g.xg(this.Za.l)==g.xg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.C)(c,function(a){this.P(a)},this)};
X7.prototype.setPlayerContextData=X7.prototype.ka;X7.prototype.W=function(){var a=this.g.C.id,b=g.La(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
X7.prototype.getOtherConnectedRemoteId=X7.prototype.W;X7.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.G)():window.NaN};
X7.prototype.getReconnectTimeout=X7.prototype.F;X7.prototype.Y=function(){return this.A||"UNSUPPORTED"};
X7.prototype.getAutoplayMode=X7.prototype.Y;X7.prototype.ba=function(){return this.D||""};
X7.prototype.getAutoplayVideoId=X7.prototype.ba;X7.prototype.oa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.au(a.g);a.start()}};
X7.prototype.reconnect=X7.prototype.oa;X7.prototype.fa=function(a,b){c8(this,a,b);eCa(this)};
X7.prototype.sendMessage=X7.prototype.fa;g.A(d8,d7);g.h=d8.prototype;g.h.ne=function(a){return this.cd.$_gs(a)};
g.h.contains=function(a){return!!this.cd.$_c(a)};
g.h.get=function(a){return this.cd.$_g(a)};
g.h.start=function(){this.cd.$_st()};
g.h.add=function(a,b,c){this.cd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.cd.$_r(a,b,c)};
g.h.Ep=function(a,b,c,d){this.cd.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.l.length;a<b;++a)this.cd.$_ubk(this.l[a]);this.l.length=0;this.cd=null;d8.Z.U.call(this)};
g.h.OU=function(){this.P("screenChange")};
g.h.QQ=function(){this.P("onlineScreenChange")};
m7.prototype.$_st=m7.prototype.start;m7.prototype.$_gspc=m7.prototype.PU;m7.prototype.$_gsppc=m7.prototype.aE;m7.prototype.$_c=m7.prototype.contains;m7.prototype.$_g=m7.prototype.get;m7.prototype.$_a=m7.prototype.add;m7.prototype.$_un=m7.prototype.Ep;m7.prototype.$_r=m7.prototype.remove;m7.prototype.$_gs=m7.prototype.ne;m7.prototype.$_gos=m7.prototype.ZD;m7.prototype.$_s=m7.prototype.subscribe;m7.prototype.$_ubk=m7.prototype.Ld;var e8=null,f8=null,u8=null,j8=[];g.p(v8,g.K);g.h=v8.prototype;
g.h.U=function(){g.K.prototype.U.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.MB,this);this.g.unsubscribe("remotePlayerChange",this.Hl,this);this.g.unsubscribe("remoteQueueChange",this.Qo,this);this.g.unsubscribe("autoplayUpNext",this.iB,this);this.g.unsubscribe("previousNextChange",this.JB,this);this.g.unsubscribe("nowAutoplaying",this.BB,this);this.g.unsubscribe("autoplayDismissed",this.hB,this);this.g=this.F=null};
g.h.nA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(y8(this)){if(!R7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":R7(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.rj(c[0],c[1]);break;case "control_subtitles_set_track":z8(this,c[0]);break;case "control_set_audio_track":c=c[0],y8(this)&&this.g.ov(this.l.ea(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();A8(this,0==c?void 0:c);break;case "control_seek":A8(this,c[0]);break;case "control_subtitles_set_track":z8(this,c[0]);break;case "control_set_audio_track":c=c[0],y8(this)&&this.g.ov(this.l.ea(1).videoId,c)}};
g.h.OO=function(a){this.K.fI(a)};
g.h.rU=function(a){this.nA("control_subtitles_set_track",g.Wb(a)?null:a)};
g.h.iD=function(){var a=this.l.zc("captions","track");g.Wb(a)||z8(this,a)};
g.h.zB=function(a){if(y8(this)){this.g.unsubscribe("remotePlayerChange",this.Hl,this);var b=Math.round(a.volume);a=!!a.muted;var c=R7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.M.start();this.g.subscribe("remotePlayerChange",this.Hl,this)}};
g.h.iQ=function(){g.Wb(this.C)||zCa(this,this.C);this.D=!1};
g.h.MB=function(a,b){this.B.stop();2==b&&this.fD()};
g.h.Hl=function(){if(y8(this)){this.A.stop();var a=R7(this.g);switch(a.g){case 1081:case 1:x8(this,new g.GO(8));this.eD();break;case 1085:case 3:x8(this,new g.GO(9));break;case 1083:case 0:x8(this,new g.GO(2));this.I.stop();w8(this,this.l.ea().lengthSeconds);break;case 1084:x8(this,new g.GO(4));break;case 2:x8(this,new g.GO(4));w8(this,M7(a));break;case -1:x8(this,new g.GO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.V("YTP_MDX_PLAYER_ERROR")},x8(this,new g.GO(128,a))}a=R7(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,zCa(this,a));a=R7(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.M.isActive()||this.LD()}else yCa(this)};
g.h.JB=function(){this.l.P("mdxpreviousnextchange")};
g.h.Qo=function(){y8(this)||yCa(this)};
g.h.rH=function(){this.g.qx()};
g.h.iB=function(a){a&&(a=g.kE("/watch_queue_ajax",{method:"GET",hd:{action_get_watch_queue_item:1,video_id:a},Hb:(0,g.z)(this.rS,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.rS=function(a,b){var c=new g.HN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.P("mdxautoplayupnext",c)};
g.h.BB=function(a){(0,window.isNaN)(a)||this.l.P("mdxnowautoplaying",a)};
g.h.hB=function(){this.l.P("mdxautoplaycanceled")};
g.h.UM=function(a,b){-1==R7(this.g).g?A8(this,a):b&&this.g.XD(a)};
g.h.LD=function(){if(y8(this)){var a=R7(this.g);this.o.Ba(this.V);a.muted?this.l.mute():this.l.Xf();this.l.setVolume(a.volume);this.V=this.o.O(this.l,"onVolumeChange",this.zB)}};
g.h.eD=function(){this.A.stop();if(!this.g.ha()){var a=R7(this.g);a.kb()&&x8(this,new g.GO(8));w8(this,M7(a));this.A.start()}};
g.h.fD=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(B8,g.W);B8.prototype.A=function(a){BCa(this,a.state)};g.p(C8,g.KZ);C8.prototype.I=function(){var a=this.l.zc("remote","receivers");a&&1<a.length&&!this.l.zc("remote","quickCast")?(this.F=g.jb(a,this.B,this),g.LZ(this,(0,g.H)(a,this.B)),a=this.l.zc("remote","currentReceiver"),this.qf(this.B(a)),this.enable(!0)):this.enable(!1)};
C8.prototype.B=function(a){return a.key};
C8.prototype.pf=function(a){return"cast-selector-receiver"==a?g.V("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
C8.prototype.ud=function(a){g.KZ.prototype.ud.call(this,a);this.l.Jd("remote","currentReceiver",this.F[a]);this.A.Pb()};g.p(D8,g.vV);g.h=D8.prototype;g.h.create=function(){sCa(g.eM(g.Y(this.g)));this.C.push(g.PF("yt-remote-before-disconnect",this.KO,this));this.C.push(g.PF("yt-remote-connection-change",this.yR,this));this.C.push(g.PF("yt-remote-receiver-availability-change",this.KB,this));this.C.push(g.PF("yt-remote-auto-connect",this.wR,this));this.C.push(g.PF("yt-remote-receiver-resumed",this.vR,this));this.KB()};
g.h.load=function(){this.g.lt();g.vV.prototype.load.call(this);this.B=new v8(this,this.g,this.l);var a=(a=xCa())?a.currentTime:0;var b=t8()?new Q7(o8(),void 0):null;0==a&&b&&(a=M7(R7(b)));0!=a&&(this.H=a||0,this.g.P("progresssync",a,void 0));ACa(this,this.D,this.D);g.V_(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.A=this.o;g.Ze(this.B,this.l);this.l=this.B=null;g.vV.prototype.unload.call(this);g.V_(this.g.app,5)};
g.h.U=function(){g.QF(this.C);g.vV.prototype.U.call(this)};
g.h.wl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.nA.apply(this.B,[].concat([a],g.qa(c)))};
g.h.bI=function(){return this.loaded?this.B.suggestion:null};
g.h.Lf=function(){return this.l?R7(this.l).Lf:!1};
g.h.hasNext=function(){return this.l?R7(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.IM=function(){var a=R7(this.l),b=this.g.ea();return{allowSeeking:this.g.ed(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+K7(a):a.A,isPeggedToLive:1>=(a.C?a.o+K7(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+K7(a):a.o,seekableStart:0<a.B?a.B+K7(a):a.B}};
g.h.JM=function(){this.l&&this.l.VD()};
g.h.KM=function(){this.l&&this.l.WD()};
g.h.KO=function(a){1==a&&(this.I=this.l?R7(this.l):null)};
g.h.yR=function(){var a=t8()?new Q7(o8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Ye(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.ea().videoId&&this.g.Pz(a.videoId,M7(a)));this.g.P("videodatachange","newdata",this.g.ea(),3)};
g.h.KB=function(){this.F=[this.o].concat(uCa());var a=p8()||this.o;E8(this,a);this.g.sa("onMdxReceiversChange")};
g.h.wR=function(){var a=p8();E8(this,a)};
g.h.vR=function(){this.A=p8()};
g.h.HM=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?G7():E8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&G7(),!0):!1}};
g.h.LM=function(){V7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Wc=function(){return!1};g.fY.remote=D8;})(_yt_player);
