(function(g){var window=this;var IAa=function(a,b){return g.Ub(a,b)},Y5=function(a){g.Fm(a,"zx",g.xb());
return a},Z5=function(a,b,c){g.ya(c)||(c=[String(c)]);
g.Im(a.g,b,c)},JAa=function(a,b){var c=[];
g.nk(b,function(a){try{var b=g.VC.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.UC(b)&&c.push(a):c.push(a)},a);
return c},KAa=function(a,b){var c=JAa(a,b);
(0,g.B)(c,function(a){g.VC.prototype.remove.call(this,a)},a)},LAa=function(a,b,c,d){var e=new g.wm(null,void 0);
a&&g.xm(e,a);b&&g.ym(e,b);c&&g.zm(e,c);d&&g.Am(e,d);return e},MAa=function(a){g.PF[a]&&(a=g.PF[a],(0,g.B)(a,function(a){g.NF[a]&&delete g.NF[a]}),a.length=0)},NAa=function(a){var b=g.MF();
if(b)if(b.clear(a),a)MAa(a);else for(var c in g.PF)MAa(c)},$5=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.qm;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",OAa(this,a.capabilities||""),PAa(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},OAa=function(a,b){a.capabilities.clear();
(0,g.Hd)(b.split(","),g.Ea(IAa,QAa)).forEach(function(b){a.capabilities.add(b)})},PAa=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},a6=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},b6=function(a,b){return!!b&&(a.id==b||a.uuid==b)},RAa=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},SAa=function(a){return new a6(a)},TAa=function(a){return g.ya(a)?(0,g.H)(a,SAa):[]},c6=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},d6=function(a){return g.ya(a)?"["+(0,g.H)(a,c6).join(",")+"]":"null"},e6=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},UAa=function(a){return(0,g.H)(a,function(a){return{key:a.id,
name:a.name}})},f6=function(a,b){return g.Ka(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},g6=function(a,b){return g.Ka(a,function(a){return b6(a,b)})},VAa=function(){var a=(0,g.JG)();
a&&KAa(a,a.g.Od(!0))},h6=function(){var a=g.MG("yt-remote-connected-devices")||[];
g.fb(a);return a},WAa=function(a){if(g.Qa(a))return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.H)(a,function(a,b){return 0==b?a:a.substring(c.length)})},XAa=function(a){g.LG("yt-remote-connected-devices",a,86400)},j6=function(){if(i6)return i6;
var a=g.MG("yt-remote-device-id");a||(a=e6(),g.LG("yt-remote-device-id",a,31536E3));for(var b=h6(),c=1,d=a;g.Pa(b,d);)c++,d=a+"#"+c;return i6=d},k6=function(){var a=h6(),b=j6();
g.Pa(a,b);g.OG()&&g.ib(a,b);a=WAa(a);if(g.Qa(a))try{g.wG("remote_sid")}catch(c){}else try{g.vG("remote_sid",a.join(","),-1)}catch(c){}},YAa=function(){return g.MG("yt-remote-session-browser-channel")},ZAa=function(){return g.MG("yt-remote-local-screens")||[]},$Aa=function(){g.LG("yt-remote-lounge-token-expiration",!0,86400)},aBa=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.H)(ZAa(),function(a){return a.loungeToken}),c=(0,g.H)(a,function(a){return a.loungeToken});
(0,g.fm)(c,function(a){return!g.Pa(b,a)})&&$Aa();
g.LG("yt-remote-local-screens",a,31536E3)},bBa=function(a,b){g.LG("yt-remote-session-browser-channel",a);
g.LG("yt-remote-session-screen-id",b);var c=h6(),d=j6();g.Pa(c,d)||c.push(d);XAa(c);k6()},l6=function(a){a||(g.NG("yt-remote-session-screen-id"),g.NG("yt-remote-session-video-id"));
k6();a=h6();g.Ua(a,j6());XAa(a)},cBa=function(){if(!m6){var a=g.fD();
a&&(m6=new g.PC(a))}return m6?!!m6.get("yt-remote-use-staging-server"):!1},dBa=function(){var a=window.document.createElement("a");
g.Wc(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Cb(a)},eBa=function(a,b){var c=g.zd("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.Xc(c,g.ae("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},fBa=function(){var a=dBa(),b=window.document.getElementById(a),c=b&&g.aF(b,"loaded");
c||b&&!c||(b=eBa(a,function(){g.aF(b,"loaded")||(g.$E(b,"loaded","true"),g.TF(a),g.OD(g.Ea(NAa,a),0))}))},n6=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},gBa=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},o6=function(a){a.length?hBa(a.shift(),function(){o6(a)}):p6()},iBa=function(a){return"chrome-extension://"+a+q6},hBa=function(a,
b,c){var d=window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},r6=function(a){return 0<=window.navigator.userAgent.indexOf(a)},p6=function(){var a=gBa();
a&&a(!1,"No cast extension found")},s6=function(){if(jBa){var a=2,b=gBa(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;hBa("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",p6,c)}},kBa=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(s6(),a({command:"cast.sender.init"}))},lBa=function(){s6();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);o6(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+q6,"//www.gstatic.com/eureka/clank"+q6])},t6=function(a,b,c){g.K.call(this);
this.C=null!=c?(0,g.z)(a,c):a;this.ed=b;this.B=(0,g.z)(this.oI,this);this.g=!1;this.l=0;this.o=this.xa=null;this.A=[]},u6=function(){},v6=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.D=d||1;this.B=45E3;this.A=new g.Mm(this);this.l=new g.rg;this.l.setInterval(250)},nBa=function(a,b,c){a.uj=1;
a.lh=Y5(b.clone());a.Ii=c;a.C=!0;mBa(a,null)},w6=function(a,b,c,d,e){a.uj=1;
a.lh=Y5(b.clone());a.Ii=null;a.C=c;e&&(a.MC=!1);mBa(a,d)},mBa=function(a,b){a.Zj=(0,g.G)();
x6(a);a.Eh=a.lh.clone();Z5(a.Eh,"t",a.D);a.Wl=0;a.Rc=a.g.Rq(a.g.Ql()?b:null);0<a.yr&&(a.Zo=new g.Pk((0,g.z)(a.bE,a,a.Rc),a.yr));a.A.R(a.Rc,"readystatechange",a.pT);var c=a.ji?g.ac(a.ji):{};a.Ii?(a.Jp="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.Rc.send(a.Eh,a.Jp,a.Ii,c)):(a.Jp="GET",a.MC&&!g.vd&&(c.Connection="close"),a.Rc.send(a.Eh,a.Jp,null,c));a.g.qf(1)},qBa=function(a,b,c){for(var d=!0;!a.Sh&&a.Wl<c.length;){var e=oBa(a,c);
if(e==y6){4==b&&(a.mh=4,z6(15),d=!1);break}else if(e==pBa){a.mh=4;z6(16);d=!1;break}else A6(a,e)}4==b&&0==c.length&&(a.mh=1,z6(17),d=!1);a.wf=a.wf&&d;d||(B6(a),C6(a))},oBa=function(a,b){var c=a.Wl,d=b.indexOf("\n",c);
if(-1==d)return y6;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return pBa;d+=1;if(d+c>b.length)return y6;var e=b.substr(d,c);a.Wl=d+c;return e},sBa=function(a,b){a.Zj=(0,g.G)();
x6(a);var c=b?window.location.hostname:"";a.Eh=a.lh.clone();g.Fm(a.Eh,"DOMAIN",c);g.Fm(a.Eh,"t",a.D);try{a.xf=new window.ActiveXObject("htmlfile")}catch(n){B6(a);a.mh=7;z6(22);C6(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in D6)k=D6[l];else if(l in rBa)k=D6[l]=rBa[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=
m.toString(16).toUpperCase()}k=D6[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.Yc(g.tc("b/12014412"),d);a.xf.open();a.xf.write(g.Oc(c));a.xf.close();a.xf.parentWindow.m=(0,g.z)(a.xS,a);a.xf.parentWindow.d=(0,g.z)(a.ZB,a,!0);a.xf.parentWindow.rpcClose=(0,g.z)(a.ZB,a,!1);c=a.xf.createElement("DIV");a.xf.parentWindow.document.body.appendChild(c);d=g.Fc(a.Eh.toString());d=g.pb(g.Cc(d));d=g.Yc(g.tc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.Oc(d);
a.g.qf(1)},x6=function(a){a.jv=(0,g.G)()+a.B;
tBa(a,a.B)},tBa=function(a,b){if(null!=a.tk)throw Error("WatchDog timer not null");
a.tk=E6((0,g.z)(a.OS,a),b)},F6=function(a){a.tk&&(g.w.clearTimeout(a.tk),a.tk=null)},C6=function(a){a.g.iy()||a.Sh||a.g.Mo(a)},B6=function(a){F6(a);
g.Ze(a.Zo);a.Zo=null;a.l.stop();g.Sm(a.A);if(a.Rc){var b=a.Rc;a.Rc=null;b.abort();b.dispose()}a.xf&&(a.xf=null)},A6=function(a,b){try{a.g.SB(a,b),a.g.qf(4)}catch(c){}},vBa=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;uBa(a,b,function(e){e?c(!0):g.w.setTimeout(function(){vBa(a,b,c,d,f)},f)})}},uBa=function(a,b,c){var d=new window.Image;
d.onload=function(){try{G6(d),c(!0)}catch(e){}};
d.onerror=function(){try{G6(d),c(!1)}catch(e){}};
d.onabort=function(){try{G6(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{G6(d),c(!1)}catch(e){}};
g.w.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},G6=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},wBa=function(a){this.g=a;
this.l=new u6},xBa=function(a){var b=H6(a.g,a.xk,"/mail/images/cleardot.gif");
Y5(b);vBa(b.toString(),5E3,(0,g.z)(a.AH,a),3,2E3);a.qf(1)},J6=function(a){var b=a.g.H;
if(null!=b)z6(5),b?(z6(11),I6(a.g,a,!1)):(z6(12),I6(a.g,a,!0));else if(a.se=new v6(a,void 0,void 0,void 0),a.se.ji=a.vr,b=a.g,b=H6(b,b.Ql()?a.Vk:null,a.xr),z6(5),!g.td||g.pc(10))Z5(b,"TYPE","xmlhttp"),w6(a.se,b,!1,a.Vk,!1);else{Z5(b,"TYPE","html");var c=a.se;a=!!a.Vk;c.uj=3;c.lh=Y5(b.clone());sBa(c,a)}},K6=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new u6;this.F=a||null;this.H=null!=b?b:null;this.C=c||!1},yBa=function(a,b){this.g=a;
this.map=b;this.context=null},zBa=function(a){g.af.call(this,"statevent",a)},ABa=function(a,b){g.af.call(this,"timingevent",a);
this.size=b},BBa=function(a){g.af.call(this,"serverreachability",a)},EBa=function(a){CBa(a);
if(3==a.g){var b=a.Cl++,c=a.Cn.clone();g.Fm(c,"SID",a.o);g.Fm(c,"RID",b);g.Fm(c,"TYPE","terminate");L6(a,c);b=new v6(a,a.o,b,void 0);b.uj=2;b.lh=Y5(c.clone());(new window.Image).src=b.lh;b.Zj=(0,g.G)();x6(b)}DBa(a)},FBa=function(a){a.VH(1,0);
a.Cn=H6(a,null,a.ur);M6(a)},CBa=function(a){a.bh&&(a.bh.abort(),a.bh=null);
a.uc&&(a.uc.cancel(),a.uc=null);a.ng&&(g.w.clearTimeout(a.ng),a.ng=null);N6(a);a.Td&&(a.Td.cancel(),a.Td=null);a.eh&&(g.w.clearTimeout(a.eh),a.eh=null)},GBa=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new yBa(a.pO++,b));2!=a.g&&3!=a.g||M6(a)},M6=function(a){a.Td||a.eh||(a.eh=E6((0,g.z)(a.XB,a),0),a.mj=0)},IBa=function(a,b){if(1==a.g){if(!b){a.Cl=Math.floor(1E5*Math.random());
var c=a.Cl++,d=new v6(a,"",c,void 0);d.ji=null;var e=O6(a),f=a.Cn.clone();g.Fm(f,"RID",c);g.Fm(f,"CVER","1");L6(a,f);nBa(d,f,e);a.Td=d;a.g=2}}else 3==a.g&&(b?HBa(a,b):0==a.l.length||a.Td||HBa(a))},HBa=function(a,b){if(b)if(6<a.Uh){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Cl-1;var d=O6(a)}else c=b.F,d=b.Ii;else c=a.Cl++,d=O6(a);var e=a.Cn.clone();g.Fm(e,"SID",a.o);g.Fm(e,"RID",c);g.Fm(e,"AID",a.Jj);L6(a,e);c=new v6(a,a.o,c,a.mj+1);c.ji=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.Td=c;nBa(c,e,d)},L6=function(a,b){if(a.qd){var c=a.qd.Ox();
c&&g.Lb(c,function(a,c){g.Fm(b,c,a)})}},O6=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.Uh&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.Uh?e:f-d;try{g.Lb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},JBa=function(a){a.uc||a.ng||(a.D=1,a.ng=E6((0,g.z)(a.WB,a),0),a.aj=0)},P6=function(a){if(a.uc||a.ng||3<=a.aj)return!1;
a.D++;a.ng=E6((0,g.z)(a.WB,a),KBa(a,a.aj));a.aj++;return!0},I6=function(a,b,c){a.Ip=c;
a.Hf=b.vg;a.C||FBa(a)},N6=function(a){null!=a.Wh&&(g.w.clearTimeout(a.Wh),a.Wh=null)},KBa=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Q6=function(a,b){if(2==b||9==b){var c=null;
a.qd&&(c=null);var d=(0,g.z)(a.kU,a);c||(c=new g.wm("//www.google.com/images/cleardot.gif"),Y5(c));uBa(c.toString(),1E4,d)}else z6(2);LBa(a,b)},LBa=function(a,b){a.g=0;
a.qd&&a.qd.Iw(b);DBa(a);CBa(a)},DBa=function(a){a.g=0;
a.Hf=-1;if(a.qd)if(0==a.A.length&&0==a.l.length)a.qd.Gq();else{g.Xa(a.A);var b=g.Xa(a.l);a.A.length=0;a.l.length=0;a.qd.Gq(b)}},H6=function(a,b,c){var d=g.Gm(c);
if(""!=d.l)b&&g.ym(d,b+"."+d.l),g.zm(d,d.B);else{var e=window.location;d=LAa(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.Ik&&g.Lb(a.Ik,function(a,b){g.Fm(d,b,a)});
g.Fm(d,"VER",a.Uh);L6(a,d);return d},E6=function(a,b){if(!g.Aa(a))throw Error("Fn must not be null and must be a function");
return g.w.setTimeout(function(){a()},b)},z6=function(a){R6.dispatchEvent(new zBa(R6,a))},MBa=function(){},NBa=function(a,b){this.action=a;
this.params=b||{}},S6=function(a,b){g.K.call(this);
this.g=new g.Vt(this.oS,0,this);g.L(this,this.g);this.ed=5E3;this.l=0;if(g.Aa(a))b&&(a=(0,g.z)(a,b));else if(a&&g.Aa(a.handleEvent))a=(0,g.z)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},T6=function(a,b,c){this.K=a;
this.C=b;this.o=new g.OC;this.l=new S6(this.PU,this);this.g=this.Ya=null;this.I=!1;this.B=null;this.H="";this.F=this.A=0;this.D=[];this.M=c||!1},OBa=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Ip,sessionId:a.g.o,arrayId:a.g.Jj}},PBa=function(a,b){a.F=b||0;
a.l.stop();a.g&&(3==a.g.g&&IBa(a.g),EBa(a.g));a.F=0},U6=function(a){return!!a.g&&3==a.g.g},QBa=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},V6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Ig(a)||"";b&&(this.port=":"+b);this.domain=g.Hg(a)||"";a=g.Jb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Bb(a,"10.0")&&(this.l=!1))},W6=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.Rg(c+b,{})},X6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,Hb:g.Ea(a.A,d,!0),onError:g.Ea(a.o,e),wd:g.Ea(a.B,e)};c&&(a.Lb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.lE(b,a)},UBa=function(){var a=RBa;
SBa();Y6.push(a);TBa(Y6)},Z6=function(a,b){SBa();
var c=Y6,d=VBa(a,String(b));g.Qa(c)?WBa(d):(TBa(c),(0,g.B)(c,function(a){a(d)}))},SBa=function(){Y6||(Y6=g.x("yt.mdx.remote.debug.handlers_")||[],g.va("yt.mdx.remote.debug.handlers_",Y6,void 0))},WBa=function(a){var b=($6+1)%50;
$6=b;a7[b]=a;b7||(b7=49==b)},TBa=function(a){var b=a7;
if(b[0]){var c=$6,d=b7?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.B)(a,function(a){a(e)})}while(d!=c);
a7=Array(50);$6=-1;b7=!1}},VBa=function(a,b){var c=((0,g.G)()-XBa)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},c7=function(a){g.FF.call(this);
this.D=a;this.g=[]},YBa=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},ZBa=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Hd)(a.g,function(a){return!!f6(b,a)});
for(var d=0,e=b.length;d<e;d++)c=YBa(a,b[d])||c;return c},$Ba=function(a,b){var c=a.g.length;
a.g=(0,g.Hd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},d7=function(a,b,c,d){g.FF.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.xa=window.NaN},f7=function(a){c7.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;e7(this);this.info("Initializing with "+d6(this.g))},aCa=function(a){if(a.g.length){var b=(0,g.H)(a.g,function(a){return a.id}),c=W6(a.o,"/pairing/get_lounge_token_batch");
X6(a.o,c,{screen_ids:b.join(",")},(0,g.z)(a.AI,a),(0,g.z)(a.zI,a))}},e7=function(a){var b=TAa(ZAa());
b=(0,g.Hd)(b,function(a){return!a.uuid});
return ZBa(a,b)},g7=function(a,b){aBa((0,g.H)(a.g,RAa));
b&&$Aa()},i7=function(a,b){g.FF.call(this);
this.C=b;var c=g.MG("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Pa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;h7("Initialized with "+g.yg(this.g))},bCa=function(a,b,c){var d=W6(a.B,"/pairing/get_screen_availability");
X6(a.B,d,{lounge_token:b.token},(0,g.z)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.z)(function(){c(!1)},a))},j7=function(a,b){a:if(g.Pb(b)!=g.Pb(a.g))var c=!1;
else{c=g.Rb(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(h7("Updated online screens: "+g.yg(a.g)),a.g=b,a.P("screenChange"));cCa(a)},k7=function(a){(0,window.isNaN)(a.o)||g.QD(a.o);
a.o=g.OD((0,g.z)(a.tu,a),0<a.A&&a.A<(0,g.G)()?2E4:1E4)},h7=function(a){Z6("OnlineScreenService",a)},dCa=function(a){var b={};
(0,g.B)(a.C(),function(a){a.token?b[a.token]=a.id:this.gc("Requesting availability of screen w/o lounge token.")});
return b},cCa=function(a){a=g.Rb(g.Mb(a.g,function(a){return a}));
g.fb(a);a.length?g.LG("yt-remote-online-screen-ids",a.join(","),60):g.NG("yt-remote-online-screen-ids")},l7=function(a){c7.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};eCa(this)},gCa=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.ke();if(k=(c?g6(k,c):null)||g6(k,b)){k.uuid=b;var l=m7(a,k);bCa(a.l,l,function(a){e(a?l:null)})}else c?fCa(a,c,(0,g.z)(function(a){var f=m7(this,new a6({name:d,
screenId:c,loungeToken:a,dialId:b||""}));bCa(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},hCa=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},fCa=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={Lb:{screen_ids:b},method:"POST",context:a,Hb:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.lE(W6(a.C,"/pairing/get_lounge_token_batch"),e)},iCa=function(a){a.g=a.o.ke();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+d6(a.g))},eCa=function(a){n7(a);
a.o=new f7(a.C);a.o.subscribe("screenChange",(0,g.z)(a.RI,a));iCa(a);a.A=TAa(g.MG("yt-remote-automatic-screen-cache")||[]);n7(a);a.info("Initializing automatic screens: "+d6(a.A));a.l=new i7(a.C,(0,g.z)(a.ke,a,!0));a.l.subscribe("screenChange",(0,g.z)(function(){this.P("onlineScreenChange")},a))},m7=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=g6(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.LG("yt-remote-automatic-screen-cache",(0,g.H)(a.A,RAa)));n7(a);a.B[b.uuid]=b.id;g.LG("yt-remote-device-id-map",a.B,31536E3);return b},n7=function(a){a.B=g.MG("yt-remote-device-id-map")||{}},o7=function(a,b,c){g.FF.call(this);
this.M=c;this.H=a;this.l=b;this.o=null},p7=function(a,b){Z6(a.M,b)},q7=function(a,b){o7.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.z)(this.VU,this);this.B=(0,g.z)(this.ZS,this);this.A=g.OD((0,g.z)(function(){jCa(this,null)},this),12E4)},kCa=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.yg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.y,(0,g.z)(function(){p7(this,"Failed to send message: getMdxSessionStatus.")},a)):p7(a,"Sending yt message without session: "+g.yg(b))},jCa=function(a,b){g.QD(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.z)(a.No,a),d=(0,g.z)(a.qe,a);a.Zx(b,c,d,5)}}else a.qe(Error("Waiting for session status timed out."))},r7=function(a,b,c){o7.call(this,a,b,"DialSession");
this.A=this.F=null;this.I="";this.N=c;this.B=null;this.D=g.y;this.C=window.NaN;this.K=(0,g.z)(this.YU,this);this.g=g.y},lCa=function(a){a.g=a.H.iE(a.I,a.l.label,a.l.friendlyName,(0,g.z)(function(a){this.g=g.y;
this.No(a)},a),(0,g.z)(function(a){this.g=g.y;
this.qe(a)},a))},mCa=function(a){var b={};
b.pairingCode=a.I;b.theme=a.N;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}cBa()&&(b.env_useStageMdx=1);return g.Pg(b)},s7=function(a,b){o7.call(this,a,b,"ManualSession");
this.g=g.OD((0,g.z)(this.Kj,this,null),150)},t7=function(a,b,c,d){g.FF.call(this);
this.l=a;this.D=b||"233637DE";this.C=c||"cl";this.F=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.z)(this.CR,this)},nCa=function(a,b){return b?g.Ka(a.o,function(a){return b6(b,a.label)},a):null},u7=function(a){Z6("Controller",a)},RBa=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},v7=function(a){return a.B||!!a.o.length||!!a.g},w7=function(a,b,c){b!=a.g&&(g.Ze(a.g),(a.g=b)?(c?a.P("yt-remote-cast2-receiver-resumed",b.l):a.P("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.z)(a.UB,a,b)),b.o?a.P("yt-remote-cast2-session-change",b.o):c&&a.g.Kj(null)):a.P("yt-remote-cast2-session-change",null))},oCa=function(a){var b=a.l.hE(),c=a.g&&a.g.l;
a=(0,g.H)(b,function(a){c&&b6(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=nCa(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},uCa=function(a,b,c,d,e,f,k){pCa()?qCa(b,e,f,k)&&(y7(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?rCa(a,c):(window.__onGCastApiAvailable=function(b,d){b?rCa(a,c):(z7("Failed to load cast API: "+d),A7(!1),y7(!1),g.NG("yt-remote-cast-available"),g.NG("yt-remote-cast-receiver"),sCa(),
c(!1))},d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):fBa():r6("CriOS")?kBa():r6("Android")&&r6("Chrome/")&&window.navigator.presentation?lBa():window.chrome&&window.navigator.presentation&&!r6("Edge")?(s6(),o6(tCa.map(iBa))):p6())):x7("Cannot initialize because not running Chrome")},sCa=function(){x7("dispose");
var a=B7();a&&a.dispose();g.va("yt.mdx.remote.cloudview.instance_",null,void 0);vCa(!1);g.RF(C7);C7.length=0},D7=function(){return!!g.MG("yt-remote-cast-installed")},wCa=function(){var a=g.MG("yt-remote-cast-receiver");
return a?a.friendlyName:null},xCa=function(){x7("clearCurrentReceiver");
g.NG("yt-remote-cast-receiver")},yCa=function(){return D7()?B7()?B7().getCastSession():(z7("getCastSelector: Cast is not initialized."),null):(z7("getCastSelector: Cast API is not installed!"),null)},F7=function(){D7()?B7()?E7()?(x7("Requesting cast selector."),B7().requestSession()):(x7("Wait for cast API to be ready to request the session."),C7.push(g.QF("yt-remote-cast2-api-ready",F7))):z7("requestCastSelector: Cast is not initialized."):z7("requestCastSelector: Cast API is not installed!")},G7=
function(a,b){E7()?B7().setConnectedScreenStatus(a,b):z7("setConnectedScreenStatus called before ready.")},pCa=function(){var a=0<=g.Jb.search(/ (CrMo|Chrome|CriOS)\//);
return g.NJ||a},zCa=function(a,b){B7().init(a,b)},qCa=function(a,b,c,d){var e=!1;
B7()||(a=new t7(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.LG("yt-remote-cast-available",a);g.UF("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){x7("onReceiverSelected: "+a.friendlyName);
g.LG("yt-remote-cast-receiver",a);g.UF("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){x7("onReceiverResumed: "+a.friendlyName);
g.LG("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){x7("onSessionChange: "+c6(a));
a||g.NG("yt-remote-cast-receiver");g.UF("yt-remote-cast2-session-change",a)}),g.va("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
x7("cloudview.createSingleton_: "+e);return e},B7=function(){return g.x("yt.mdx.remote.cloudview.instance_")},rCa=function(a,b){A7(!0);
y7(!1);zCa(a,function(a){a?(vCa(!0),g.TF("yt-remote-cast2-api-ready")):(z7("Failed to initialize cast API."),A7(!1),g.NG("yt-remote-cast-available"),g.NG("yt-remote-cast-receiver"),sCa());b(a)})},x7=function(a){Z6("cloudview",a)},z7=function(a){Z6("cloudview",a)},A7=function(a){x7("setCastInstalled_ "+a);
g.LG("yt-remote-cast-installed",a)},E7=function(){return!!g.x("yt.mdx.remote.cloudview.apiReady_")},vCa=function(a){x7("setApiReady_ "+a);
g.va("yt.mdx.remote.cloudview.apiReady_",a,void 0)},y7=function(a){g.va("yt.mdx.remote.cloudview.initializing_",a,void 0)},H7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.D=this.F=0;this.l=null;this.hasNext=this.Kf=!1;this.I=this.H=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},I7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.Kf=!1;a.hasNext=!1;a.F=0;a.D=(0,g.G)();a.B=0;a.o=0;a.H=0;a.I=0;a.A=window.NaN;a.C=!1},J7=function(a){return a.kb()?((0,g.G)()-a.D)/1E3:0},K7=function(a,b){a.F=b;
a.D=(0,g.G)()},L7=function(a){switch(a.g){case 1:case 1081:return((0,g.G)()-a.D)/1E3+a.F;
case -1E3:return 0}return a.F},M7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&I7(a)},N7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.bc(a.l);b.hasPrevious=a.Kf;b.hasNext=a.hasNext;b.playerTime=a.F;b.playerTimeAt=a.D;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.H;b.loadedTime=a.I;b.liveIngestionTime=a.A;return b},P7=function(a,b){g.FF.call(this);
this.g=0;this.A=a;this.C=[];this.B=new g.eC;this.o=this.l=null;this.H=(0,g.z)(this.ZO,this);this.D=(0,g.z)(this.Fl,this);this.F=(0,g.z)(this.YO,this);this.I=(0,g.z)(this.mP,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.tv,this),ACa(this))):c=3;0!=c&&(b?this.tv(c):g.OD((0,g.z)(function(){this.tv(c)},this),0));
var d=yCa();d&&O7(this,d);this.subscribe("yt-remote-cast2-session-change",this.I)},Q7=function(a){return new H7(a.A.getPlayerContextData())},ACa=function(a){(0,g.B)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.Ea(this.xR,a),this))},a)},BCa=function(a){(0,g.B)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},R7=function(a,b){50>a.B.Dc()&&g.gC(a.B,b)},T7=function(a,b,c){var d=Q7(a);
K7(d,c);-1E3!=d.g&&(d.g=b);S7(a,d)},U7=function(a,b,c){a.A.sendMessage(b,c)},S7=function(a,b){BCa(a);
a.A.setPlayerContextData(N7(b));ACa(a)},O7=function(a,b){a.o&&(a.o.removeUpdateListener(a.H),a.o.removeMediaListener(a.D),a.Fl(null));
a.o=b;a.o&&(Z6("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.H),a.o.addMediaListener(a.D),a.o.media.length&&a.Fl(a.o.media[0]))},CCa=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=Q7(a);b.contentId!=d.videoId&&Z6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;K7(d,a.l.getEstimatedTime());S7(a,d)}else Z6("CP","No cast media video. Ignoring state update.")},V7=function(a,b,c){return(0,g.z)(function(a){this.gc("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.gc("Retrying "+b+" using MDx browser channel."),U7(this,b,c))},a)},W7=function(a,b,c){g.FF.call(this);
this.B=window.NaN;this.N=!1;this.I=this.H=this.K=this.M=window.NaN;this.V=[];this.A=this.D=this.o=this.Za=this.g=null;this.ma=a;this.V.push(g.pF(window,"beforeunload",(0,g.z)(this.rI,this)));this.l=[];this.Za=new H7;this.X=b.id;this.g=DCa(this,c);this.g.subscribe("handlerOpened",this.dP,this);this.g.subscribe("handlerClosed",this.aP,this);this.g.subscribe("handlerError",this.bP,this);this.g.subscribe("handlerMessage",this.cP,this);QBa(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Za.videoId;g.OG()&&g.LG("yt-remote-session-video-id",a)},this)},X7=function(a){Z6("conn",a)},DCa=function(a,b){return new T6(W6(a.ma,"/bc"),b)},Y7=function(a,b){a.P("proxyStateChange",b)},ECa=function(a){a.B=g.OD((0,g.z)(function(){X7("Connecting timeout");
this.C(1)},a),2E4)},Z7=function(a){g.QD(a.B);
a.B=window.NaN},$7=function(a){g.QD(a.M);
a.M=window.NaN},FCa=function(a){a8(a);
a.K=g.OD((0,g.z)(function(){b8(this,"getNowPlaying")},a),2E4)},a8=function(a){g.QD(a.K);
a.K=window.NaN},HCa=function(a,b){b&&(Z7(a),$7(a));
b==(U6(a.g)&&(0,window.isNaN)(a.B))?b&&(Y7(a,1),b8(a,"getSubtitlesTrack")):b?(a.W()&&a.Za.reset(),Y7(a,1),b8(a,"getNowPlaying"),GCa(a)):a.C(1)},ICa=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Za.videoId&&(g.Xb(b.params)?a.Za.l=null:a.Za.l=b.params,a.P("remotePlayerChange"))},JCa=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Za.listId=b.params.listId||a.Za.listId;M7(a.Za,c,d);a.P("remoteQueueChange")},LCa=function(a,b){b.params=b.params||{};
JCa(a,b);KCa(a,b);a.P("autoplayDismissed")},KCa=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
K7(a.Za,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Za.g&&(c=-1E3);a.Za.g=c;c=Number(b.params.loadedTime);a.Za.I=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Za.H=(0,window.isNaN)(c)?0:c;c=a.Za;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Za;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Za.g?FCa(a):a8(a);
a.P("remotePlayerChange")},MCa=function(a,b){if(-1E3!=a.Za.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Za.g=c;c=(0,window.parseInt)(b.params.currentTime,10);K7(a.Za,(0,window.isNaN)(c)?0:c);a.P("remotePlayerChange")}},NCa=function(a,b){var c="true"==b.params.muted;
a.Za.volume=(0,window.parseInt)(b.params.volume,10);a.Za.muted=c;a.P("remotePlayerChange")},OCa=function(a,b){a.D=b.params.videoId;
a.P("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},PCa=function(a,b){var c="true"==b.params.hasNext;
a.Za.Kf="true"==b.params.hasPrevious;a.Za.hasNext=c;a.P("previousNextChange")},GCa=function(a){g.QD(a.I);
a.I=g.OD((0,g.z)(a.C,a,1),864E5)},b8=function(a,b,c){c?X7("Sending: action="+b+", params="+g.yg(c)):X7("Sending: action="+b);
a.g.sendMessage(b,c)},c8=function(a){c7.call(this,"ScreenServiceProxy");
this.dd=a;this.l=[];this.l.push(this.dd.$_s("screenChange",(0,g.z)(this.TU,this)));this.l.push(this.dd.$_s("onlineScreenChange",(0,g.z)(this.YQ,this)))},UCa=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.ID("MDX_CONFIG")||b;VAa();k6();d8||(d8=new V6(b?b.loungeApiHost:void 0),cBa()&&(d8.g="/api/loungedev"));e8||(e8=g.x("yt.mdx.remote.deferredProxies_")||[],g.va("yt.mdx.remote.deferredProxies_",e8,void 0));QCa();var c=f8();if(!c){var d=new l7(d8);g.va("yt.mdx.remote.screenService_",d,void 0);c=f8();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);uCa(a,d,function(a){a?g8()&&G7(g8(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.UF("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.x("yt.mdx.remote.initialized_")&&(g.va("yt.mdx.remote.initialized_",!0,void 0),h8("Initializing: "+g.yg(b)),i8.push(g.QF("yt-remote-cast2-availability-change",function(){g.UF("yt-remote-receiver-availability-change")})),i8.push(g.QF("yt-remote-cast2-receiver-selected",function(){j8(null);
g.UF("yt-remote-auto-connect","cast-selector-receiver")})),i8.push(g.QF("yt-remote-cast2-receiver-resumed",function(){g.UF("yt-remote-receiver-resumed","cast-selector-receiver")})),i8.push(g.QF("yt-remote-cast2-session-change",RCa)),i8.push(g.QF("yt-remote-connection-change",function(a){a?G7(g8(),"YouTube TV"):k8()||(G7(null,null),xCa())})),a=l8(),b.isAuto&&(a.id+="#dial"),g.GE("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),h8(" -- with channel params: "+
g.yg(a)),SCa(a),c.start(),g8()||TCa())},WCa=function(){var a=VCa();
D7()&&g.MG("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},VCa=function(){var a=f8().dd.$_gos();
var b=m8();b&&n8()&&(f6(a,b)||a.push(b));return UAa(a)},o8=function(){var a=XCa();
!a&&D7()&&wCa()&&(a={key:"cast-selector-receiver",name:wCa()});return a},XCa=function(){var a=VCa(),b=m8();
b||(b=k8());return g.Ka(a,function(a){return b&&b6(b,a.key)?!0:!1})},m8=function(){var a=g8();
if(!a)return null;var b=f8().ke();return g6(b,a)},RCa=function(a){h8("remote.onCastSessionChange_: "+c6(a));
if(a){var b=m8();b&&b.id==a.id?G7(b.id,"YouTube TV"):(b&&p8(),q8(a,1))}else n8()&&p8()},p8=function(){E7()?B7().stopSession():z7("stopSession called before API ready.");
var a=n8();a&&(a.disconnect(1),r8(null))},s8=function(){var a=n8();
return!!a&&3!=a.getProxyState()},h8=function(a){Z6("remote",a)},f8=function(){if(!t8){var a=g.x("yt.mdx.remote.screenService_");
t8=a?new c8(a):null}return t8},g8=function(){return g.x("yt.mdx.remote.currentScreenId_")},YCa=function(a){g.va("yt.mdx.remote.currentScreenId_",a,void 0)},ZCa=function(){return g.x("yt.mdx.remote.connectData_")},j8=function(a){g.va("yt.mdx.remote.connectData_",a,void 0)},n8=function(){return g.x("yt.mdx.remote.connection_")},r8=function(a){var b=n8();
j8(null);a||YCa("");g.va("yt.mdx.remote.connection_",a,void 0);e8&&((0,g.B)(e8,function(b){b(a)}),e8.length=0);
b&&!a?g.UF("yt-remote-connection-change",!1):!b&&a&&g.UF("yt-remote-connection-change",!0)},k8=function(){var a=g.OG();
if(!a)return null;var b=f8().ke();return g6(b,a)},q8=function(a,b){m8()&&m8();
YCa(a.id);var c=new W7(d8,a,l8());c.connect(b,ZCa());c.subscribe("beforeDisconnect",function(a){g.UF("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){n8()&&r8(null)});
r8(c)},TCa=function(){var a=k8();
a?(h8("Resume connection to: "+c6(a)),q8(a,0)):(l6(),xCa(),h8("Skipping connecting because no session screen found."))},QCa=function(){var a=l8();
if(g.Xb(a)){a=j6();var b=g.MG("yt-remote-session-name")||"",c=g.MG("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.va("yt.mdx.remote.channelParams_",a,void 0)}},l8=function(){return g.x("yt.mdx.remote.channelParams_")||{}},SCa=function(a){a?(g.LG("yt-remote-session-app",a.app),g.LG("yt-remote-session-name",a.name)):(g.NG("yt-remote-session-app"),g.NG("yt-remote-session-name"));
g.va("yt.mdx.remote.channelParams_",a,void 0)},u8=function(a,b,c){g.K.call(this);
this.F=a;this.l=b;this.o=new g.CF(this);g.L(this,this.o);this.o.O(b,"onCaptionsTrackListChanged",this.qQ);this.o.O(b,"captionschanged",this.XO);this.o.O(b,"captionssettingschanged",this.qD);this.o.O(b,"videoplayerreset",this.Oo);this.o.O(b,"mdxautoplaycancel",this.zH);this.V=this.o.O(b,"onVolumeChange",this.EB);this.D=!1;this.g=c;c.subscribe("proxyStateChange",this.RB,this);c.subscribe("remotePlayerChange",this.Il,this);c.subscribe("remoteQueueChange",this.Oo,this);c.subscribe("autoplayUpNext",this.nB,
this);c.subscribe("previousNextChange",this.OB,this);c.subscribe("nowAutoplaying",this.GB,this);c.subscribe("autoplayDismissed",this.mB,this);this.suggestion=null;this.H=new g.TO(64);this.A=new g.Vt(this.mD,500,this);g.L(this,this.A);this.B=new g.Vt(this.nD,1E3,this);g.L(this,this.B);this.K=new t6(this.wU,0,this);g.L(this,this.K);this.C={};this.M=new g.Vt(this.TD,1E3,this);g.L(this,this.M);this.I=new g.Pk(this.bN,1E3,this);g.L(this,this.I);this.N=g.y;this.qD();this.Oo();this.Il()},v8=function(a,b){var c=
a.F,d=a.l.ea().lengthSeconds;
c.H=b||0;c.g.P("progresssync",b,d)},$Ca=function(a){v8(a,0);
a.A.stop();w8(a,new g.TO(64))},y8=function(a,b){if(x8(a)&&!a.D){var c=null;
b&&(c={style:a.l.Bi()},g.dc(c,b));a.g.eD(a.l.ea(1).videoId,c);a.C=Q7(a.g).l}},z8=function(a,b){var c=a.l.Uf();
if(c){var d=c.ie();var e=c.listId.toString()}var f=a.l.ea(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.Fj;var m=Q7(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};M7(m,k,l);g.t(b)&&(K7(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);U7(c,"setPlaylist",q);e||S7(c,m);w8(a,new g.TO(1))},aDa=function(a,b){if(b){var c=a.l.zc("captions","tracklist",{Wy:1});
c&&c.length?(a.l.Kd("captions","track",b),a.D=!1):(a.l.tl("captions"),a.D=!0)}else a.l.Kd("captions","track",{})},x8=function(a){return Q7(a.g).videoId==a.l.ea(1).videoId},w8=function(a,b){a.B.stop();
var c=a.H;if(!g.aP(c,b)){var d=g.X(b,2);d!=g.X(a.H,2)&&g.WU(a.l,d);a.H=b;bDa(a.F,c,b)}},A8=function(a){g.W.call(this,{G:"div",
L:"ytp-remote",J:[{G:"div",L:"ytp-remote-display-status",J:[{G:"div",L:"ytp-remote-display-status-icon",J:[g.koa()]},{G:"div",L:"ytp-remote-display-status-text",J:["{{statustext}}"]}]}]});this.l=new g.CV(this,250);g.L(this,this.l);this.o=a;this.O(a,"presentingplayerstatechange",this.A);cDa(this,g.TU(a))},cDa=function(a,b){if(3==a.o.Ta()){var c={RECEIVER_NAME:a.o.zc("remote","currentReceiver").name};
c=g.X(b,128)?g.V("YTP_MDX_STATUS_ERROR_2",c):b.kb()||g.X(b,4)?g.V("YTP_MDX_STATUS_PLAYING_2",c):g.V("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.l.show()}else a.l.hide()},B8=function(a,b){g.GZ.call(this,g.V("YTP_MDX_TITLE"),0,a,b);
this.l=a;this.F={};this.O(a,"onMdxReceiversChange",this.I);this.O(a,"presentingplayerstatechange",this.I);this.I()},C8=function(a){g.qV.call(this,a);
g.QG({YTP_MDX_CAST_SELECTOR:"\u0414\u043e\u0431\u0430\u0432\u0438\u0442\u044c",YTP_MDX_MY_COMPUTER:"\u042d\u0442\u043e\u0442 \u043a\u043e\u043c\u043f\u044c\u044e\u0442\u0435\u0440",YTP_MDX_PLAYER_ERROR:"\u0412\u0438\u0434\u0435\u043e \u043d\u0435\u0434\u043e\u0441\u0442\u0443\u043f\u043d\u043e \u0434\u043b\u044f \u0443\u0434\u0430\u043b\u0435\u043d\u043d\u043e\u0433\u043e \u0432\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u044f.",YTP_MDX_STATUS_CONNECTED_2:'\u0423\u0441\u0442\u0430\u043d\u043e\u0432\u043b\u0435\u043d\u043e \u043f\u043e\u0434\u043a\u043b\u044e\u0447\u0435\u043d\u0438\u0435 \u043a \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0443 "$RECEIVER_NAME"',
YTP_MDX_STATUS_ERROR_2:'\u041e\u0448\u0438\u0431\u043a\u0430 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',YTP_MDX_STATUS_PLAYING_2:'\u0412\u043e\u0441\u043f\u0440\u043e\u0438\u0437\u0432\u0435\u0434\u0435\u043d\u0438\u0435 \u043d\u0430 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u0435 "$RECEIVER_NAME"',YTP_MDX_TITLE:"\u0412\u044b\u0431\u0435\u0440\u0438\u0442\u0435 \u0443\u0441\u0442\u0440\u043e\u0439\u0441\u0442\u0432\u043e \u0434\u043b\u044f \u043f\u0440\u043e\u0441\u043c\u043e\u0442\u0440\u0430"});
this.o={key:e6(),name:g.V("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.I=this.l=null;this.F=[this.o];this.A=this.o;this.D=new g.TO(64);this.H=0;if(!g.zM(g.Y(this.g))){a=this.g;var b=g.gI(a);b&&(b=b.wo())&&(b=new B8(a,b),g.L(this,b));b=new A8(a);g.L(this,b);g.kV(a,b.element,4)}},bDa=function(a,b,c){a.D=c;
a.g.P("presentingplayerstatechange",new g.gP(c,b))},D8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)p8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.ea(1),e=d.videoId;if(c||e){var f=a.g.Uf();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.kc(l).videoId}else k=[e];f=a.g.getCurrentTime(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.Fj,index:Math.max(a.g.Vz(),0),currentTime:0==f?void 0:f}}else c=null;h8("Connecting to: "+g.yg(b));"cast-selector-receiver"==b.key?(j8(c||null),E7()?B7().setLaunchParams(c||null):z7("setLaunchParams called before ready.")):!c&&
s8()&&g8()==b.key?g.UF("yt-remote-connection-change",!0):(p8(),j8(c||null),c=f8().ke(),(c=g6(c,b.key))&&q8(c,1))}},rBa={"\x00":"\\0",
"\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},D6={"'":"\\'"},dDa={},QAa={kW:"atp",I0:"ska",X_:"que",h_:"mus",E0:"sus"};
$5.prototype.jn=function(){var a=new $5({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var m6,i6="",q6=n6("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",jBa=n6("loadCastFramework")||n6("loadCastApplicationFramework"),tCa=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.A(t6,g.K);g.h=t6.prototype;g.h.nI=function(a){this.A=arguments;this.g=!1;this.xa?this.o=(0,g.G)()+this.ed:this.xa=g.sg(this.B,this.ed)};
g.h.stop=function(){this.xa&&(g.tg(this.xa),this.xa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.U=function(){this.stop();t6.Z.U.call(this)};
g.h.oI=function(){this.o?(this.xa=g.sg(this.B,this.o-(0,g.G)()),this.o=null):(this.xa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};u6.prototype.stringify=function(a){return g.w.JSON.stringify(a,void 0)};
u6.prototype.parse=function(a){return g.w.JSON.parse(a,void 0)};g.h=v6.prototype;g.h.ji=null;g.h.wf=!1;g.h.tk=null;g.h.jv=null;g.h.Zj=null;g.h.uj=null;g.h.lh=null;g.h.Eh=null;g.h.Ii=null;g.h.Rc=null;g.h.Wl=0;g.h.xf=null;g.h.Jp=null;g.h.mh=null;g.h.Wk=-1;g.h.MC=!0;g.h.Sh=!1;g.h.yr=0;g.h.Zo=null;var pBa={},y6={};g.h=v6.prototype;g.h.setTimeout=function(a){this.B=a};
g.h.pT=function(a){a=a.target;var b=this.Zo;b&&3==g.ex(a)?b.sj():this.bE(a)};
g.h.bE=function(a){try{if(a==this.Rc)a:{var b=g.ex(this.Rc),c=this.Rc.l,d=this.Rc.getStatus();if(g.td&&!g.pc(10)||g.vd&&!g.oc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.cf&&!g.mx(this.Rc))break a;this.Sh||4!=b||7==c||(8==c||0>=d?this.g.qf(3):this.g.qf(2));F6(this);var e=this.Rc.getStatus();this.Wk=e;var f=g.mx(this.Rc);(this.wf=200==e)?(4==b&&B6(this),this.C?(qBa(this,b,f),g.cf&&this.wf&&3==b&&(this.A.R(this.l,"tick",this.mT),this.l.start())):A6(this,f),this.wf&&!this.Sh&&(4==b?this.g.Mo(this):
(this.wf=!1,x6(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.mh=3,z6(13)):(this.mh=0,z6(14)),B6(this),C6(this))}}catch(k){this.Rc&&g.mx(this.Rc)}finally{}};
g.h.mT=function(){var a=g.ex(this.Rc),b=g.mx(this.Rc);this.Wl<b.length&&(F6(this),qBa(this,a,b),this.wf&&4!=a&&x6(this))};
g.h.xS=function(a){E6((0,g.z)(this.wS,this,a),0)};
g.h.wS=function(a){this.Sh||(F6(this),A6(this,a),x6(this))};
g.h.ZB=function(a){E6((0,g.z)(this.vS,this,a),0)};
g.h.vS=function(a){this.Sh||(B6(this),this.wf=a,this.g.Mo(this),this.g.qf(4))};
g.h.cancel=function(){this.Sh=!0;B6(this)};
g.h.OS=function(){this.tk=null;var a=(0,g.G)();0<=a-this.jv?(2!=this.uj&&this.g.qf(3),B6(this),this.mh=2,z6(18),C6(this)):tBa(this,this.jv-a)};g.h=wBa.prototype;g.h.vr=null;g.h.se=null;g.h.bp=!1;g.h.jy=null;g.h.zn=null;g.h.wr=null;g.h.xr=null;g.h.Le=null;g.h.vg=-1;g.h.Vk=null;g.h.xk=null;g.h.connect=function(a){this.xr=a;a=H6(this.g,null,this.xr);z6(3);this.jy=(0,g.G)();var b=this.g.F;null!=b?(this.Vk=b[0],(this.xk=b[1])?(this.Le=1,xBa(this)):(this.Le=2,J6(this))):(Z5(a,"MODE","init"),this.se=new v6(this,void 0,void 0,void 0),this.se.ji=this.vr,w6(this.se,a,!1,null,!0),this.Le=0)};
g.h.AH=function(a){if(a)this.Le=2,J6(this);else{z6(4);var b=this.g;b.Hf=b.bh.vg;Q6(b,9)}a&&this.qf(2)};
g.h.Rq=function(a){return this.g.Rq(a)};
g.h.abort=function(){this.se&&(this.se.cancel(),this.se=null);this.vg=-1};
g.h.iy=function(){return!1};
g.h.SB=function(a,b){this.vg=a.Wk;if(0==this.Le)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.Hf=this.vg;Q6(c,2);return}this.Vk=c[0];this.xk=c[1]}else c=this.g,c.Hf=this.vg,Q6(c,2);else if(2==this.Le)if(this.bp)z6(7),this.wr=(0,g.G)();else if("11111"==b){if(z6(6),this.bp=!0,this.zn=(0,g.G)(),c=this.zn-this.jy,!g.td||g.pc(10)||500>c)this.vg=200,this.se.cancel(),z6(12),I6(this.g,this,!0)}else z6(8),this.zn=this.wr=(0,g.G)(),this.bp=!1};
g.h.Mo=function(){this.vg=this.se.Wk;if(this.se.wf)0==this.Le?this.xk?(this.Le=1,xBa(this)):(this.Le=2,J6(this)):2==this.Le&&((!g.td||g.pc(10)?!this.bp:200>this.wr-this.zn)?(z6(11),I6(this.g,this,!1)):(z6(12),I6(this.g,this,!0)));else{0==this.Le?z6(9):2==this.Le&&z6(10);var a=this.g;a.Hf=this.vg;Q6(a,2)}};
g.h.Ql=function(){return this.g.Ql()};
g.h.isActive=function(){return this.g.isActive()};
g.h.qf=function(a){this.g.qf(a)};g.h=K6.prototype;g.h.Ik=null;g.h.Td=null;g.h.uc=null;g.h.ur=null;g.h.Cn=null;g.h.zw=null;g.h.Rn=null;g.h.Cl=0;g.h.pO=0;g.h.qd=null;g.h.eh=null;g.h.ng=null;g.h.Wh=null;g.h.bh=null;g.h.Ip=null;g.h.Jj=-1;g.h.iz=-1;g.h.Hf=-1;g.h.mj=0;g.h.aj=0;g.h.Uh=8;var R6=new g.Df;g.A(zBa,g.af);g.A(ABa,g.af);g.A(BBa,g.af);g.h=K6.prototype;g.h.connect=function(a,b,c,d,e){z6(0);this.ur=b;this.Ik=c||{};d&&g.t(e)&&(this.Ik.OSID=d,this.Ik.OAID=e);this.C?(E6((0,g.z)(this.Vw,this,a),100),FBa(this)):this.Vw(a)};
g.h.Vw=function(a){this.bh=new wBa(this);this.bh.vr=null;this.bh.l=this.B;this.bh.connect(a)};
g.h.iy=function(){return 0==this.g};
g.h.XB=function(a){this.eh=null;IBa(this,a)};
g.h.WB=function(){this.ng=null;this.uc=new v6(this,this.o,"rpc",this.D);this.uc.ji=null;this.uc.yr=0;var a=this.zw.clone();g.Fm(a,"RID","rpc");g.Fm(a,"SID",this.o);g.Fm(a,"CI",this.Ip?"0":"1");g.Fm(a,"AID",this.Jj);L6(this,a);if(!g.td||g.pc(10))g.Fm(a,"TYPE","xmlhttp"),w6(this.uc,a,!0,this.Rn,!1);else{g.Fm(a,"TYPE","html");var b=this.uc,c=!!this.Rn;b.uj=3;b.lh=Y5(a.clone());sBa(b,c)}};
g.h.SB=function(a,b){if(0!=this.g&&(this.uc==a||this.Td==a))if(this.Hf=a.Wk,this.Td==a&&3==this.g)if(7<this.Uh){try{var c=this.B.parse(b)}catch(f){c=null}if(g.ya(c)&&3==c.length)if(0==c[0])a:{if(!this.ng){if(this.uc)if(this.uc.Zj+3E3<this.Td.Zj)N6(this),this.uc.cancel(),this.uc=null;else break a;P6(this);z6(19)}}else this.iz=c[1],0<this.iz-this.Jj&&37500>c[2]&&this.Ip&&0==this.aj&&!this.Wh&&(this.Wh=E6((0,g.z)(this.SO,this),6E3));else Q6(this,11)}else b!=dDa.qX.g&&Q6(this,11);else if(this.uc==a&&
N6(this),!g.D(b)){c=this.B.parse(b);g.ya(c);for(var d=0;d<c.length;d++){var e=c[d];this.Jj=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.Rn=e[2],e=e[3],null!=e?this.Uh=e:this.Uh=6,this.g=3,this.qd&&this.qd.Kw(),this.zw=H6(this,this.Ql()?this.Rn:null,this.ur),JBa(this)):"stop"==e[0]&&Q6(this,7):3==this.g&&("stop"==e[0]?Q6(this,7):"noop"!=e[0]&&this.qd&&this.qd.Jw(e),this.aj=0)}}};
g.h.SO=function(){null!=this.Wh&&(this.Wh=null,this.uc.cancel(),this.uc=null,P6(this),z6(20))};
g.h.Mo=function(a){if(this.uc==a){N6(this);this.uc=null;var b=2}else if(this.Td==a)this.Td=null,b=1;else return;this.Hf=a.Wk;if(0!=this.g)if(a.wf)1==b?(b=(0,g.G)()-a.Zj,R6.dispatchEvent(new ABa(R6,a.Ii?a.Ii.length:0,b,this.mj)),M6(this),this.A.length=0):JBa(this);else{var c=a.mh,d;if(!(d=3==c||7==c||0==c&&0<this.Hf)){if(d=1==b)this.Td||this.eh||1==this.g||2<=this.mj?d=!1:(this.eh=E6((0,g.z)(this.XB,this,a),KBa(this,this.mj)),this.mj++,d=!0);d=!(d||2==b&&P6(this))}if(d)switch(c){case 1:Q6(this,5);
break;case 4:Q6(this,10);break;case 3:Q6(this,6);break;case 7:Q6(this,12);break;default:Q6(this,2)}}};
g.h.VH=function(a){if(!g.Pa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.kU=function(a){a?z6(2):(z6(1),LBa(this,8))};
g.h.Rq=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new g.Zw;a.F=!1;return a};
g.h.isActive=function(){return!!this.qd&&this.qd.isActive(this)};
g.h.qf=function(a){R6.dispatchEvent(new BBa(R6,a))};
g.h.Ql=function(){return!(!g.td||g.pc(10))};
g.h=MBa.prototype;g.h.Kw=function(){};
g.h.Jw=function(){};
g.h.Iw=function(){};
g.h.Gq=function(){};
g.h.Ox=function(){return{}};
g.h.isActive=function(){return!0};g.A(S6,g.K);g.h=S6.prototype;g.h.oS=function(){this.ed=Math.min(3E5,2*this.ed);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.ed+15E3*Math.random();g.Wt(this.g,a);this.l=(0,g.G)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.ed=5E3};g.A(T6,MBa);g.h=T6.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Nd=function(a){return this.o.Nd(a)};
g.h.P=function(a,b){return this.o.P.apply(this.o,arguments)};
g.h.dispose=function(){this.I||(this.I=!0,g.Ze(this.o),PBa(this),g.Ze(this.l),this.l=null)};
g.h.ha=function(){return this.I};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.H="";this.l.stop();this.B=a||null;this.A=b||0;a=this.K+"/test";b=this.K+"/bind";var d=new K6(c?c.firstTestResults:null,c?c.secondTestResults:null,this.M),e=this.g;e&&(e.qd=null);d.qd=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.Jj):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.dc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.D.push(c):U6(this)&&GBa(this.g,c)};
g.h.Kw=function(){this.l.reset();this.B=null;this.A=0;if(this.D.length){var a=this.D;this.D=[];for(var b=0,c=a.length;b<c;++b)GBa(this.g,a[b])}this.P("handlerOpened")};
g.h.Iw=function(a){var b=2==a&&401==this.g.Hf;4==a||b||this.l.start();this.P("handlerError",a)};
g.h.Gq=function(a){if(!this.l.isActive())this.P("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.D.push(d)}};
g.h.Ox=function(){var a={v:2};this.H&&(a.gsessionid=this.H);0!=this.A&&(a.ui=""+this.A);0!=this.F&&(a.ui=""+this.F);this.B&&g.dc(a,this.B);return a};
g.h.Jw=function(a){"S"==a[0]?this.H=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),EBa(this.g)):this.P("handlerMessage",new NBa(a[0],a[1]))};
g.h.PU=function(){this.l.isActive();var a=this.g,b=0;a.uc&&b++;a.Td&&b++;0!=b||this.connect(this.B,this.A)};V6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
V6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
V6.prototype.B=function(a){a(Error("request timed out"))};var XBa=(0,g.G)(),Y6=null,a7=Array(50),$6=-1,b7=!1;g.A(c7,g.FF);c7.prototype.ke=function(){return this.g};
c7.prototype.contains=function(a){return!!f6(this.g,a)};
c7.prototype.get=function(a){return a?g6(this.g,a):null};
c7.prototype.info=function(a){Z6(this.D,a)};g.A(d7,g.FF);var eDa=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=d7.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.xa)&&this.gE()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.xa)||(g.QD(this.xa),this.xa=window.NaN)};
g.h.U=function(){this.stop();d7.Z.U.call(this)};
g.h.gE=function(){this.xa=window.NaN;this.g=g.lE(W6(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:this.B},timeout:5E3,Hb:(0,g.z)(this.RU,this),onError:(0,g.z)(this.QU,this),wd:(0,g.z)(this.SU,this)})};
g.h.RU=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.P("pairingComplete",new a6(c))};
g.h.QU=function(a){this.g=null;a.status&&404==a.status?this.l>=eDa.length?this.P("pairingFailed",Error("DIAL polling timed out")):(a=eDa[this.l],this.xa=g.OD((0,g.z)(this.gE,this),a),this.l++):this.P("pairingFailed",Error("Server error "+a.status))};
g.h.SU=function(){this.g=null;this.P("pairingFailed",Error("Server not responding"))};g.A(f7,c7);g.h=f7.prototype;g.h.start=function(){e7(this)&&this.P("screenChange");!g.MG("yt-remote-lounge-token-expiration")&&aCa(this);g.QD(this.l);this.l=g.OD((0,g.z)(this.start,this),1E4)};
g.h.add=function(a,b){e7(this);YBa(this,a);g7(this,!1);this.P("screenChange");b(a);a.token||aCa(this)};
g.h.remove=function(a,b){var c=e7(this);$Ba(this,a)&&(g7(this,!1),c=!0);b(a);c&&this.P("screenChange")};
g.h.Ep=function(a,b,c,d){var e=e7(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,g7(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.P("screenChange")};
g.h.U=function(){g.QD(this.l);f7.Z.U.call(this)};
g.h.AI=function(a){e7(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}g7(this,!b);b&&Z6(this.D,"Missed "+b+" lounge tokens.")};
g.h.zI=function(a){Z6(this.D,"Requesting lounge tokens failed: "+a)};g.A(i7,g.FF);g.h=i7.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.MG("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.G)()-144E5<a?0:a)?k7(this):(this.A=(0,g.G)()+3E5,g.LG("yt-remote-fast-check-period",this.A),this.tu())};
g.h.isEmpty=function(){return g.Xb(this.g)};
g.h.update=function(){h7("Updating availability on schedule.");var a=this.C(),b=g.Mb(this.g,function(b,d){return b&&!!g6(a,d)},this);
j7(this,b)};
g.h.U=function(){g.QD(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);i7.Z.U.call(this)};
g.h.tu=function(){g.QD(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=dCa(this);if(g.Pb(a)){var b=W6(this.B,"/pairing/get_screen_availability");this.l=X6(this.B,b,{lounge_token:g.Rb(a).join(",")},(0,g.z)(this.WR,this,a),(0,g.z)(this.VR,this))}else j7(this,{}),k7(this)};
g.h.WR=function(a,b){this.l=null;var c=g.Rb(dCa(this));if(g.gb(c,g.Rb(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;j7(this,d);k7(this)}else this.gc("Changing Screen set during request."),this.tu()};
g.h.VR=function(a){this.gc("Screen availability failed: "+a);this.l=null;k7(this)};
g.h.gc=function(a){Z6("OnlineScreenService",a)};g.A(l7,c7);g.h=l7.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.P("screenChange"),this.l.isEmpty()||this.P("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Ep=function(a,b,c,d){this.o.contains(a)?this.o.Ep(a,b,c,d):(a="Updating name of unknown screen: "+a.name,Z6(this.D,a),d(Error(a)))};
g.h.ke=function(a){return a?this.g:g.Wa(this.g,(0,g.Hd)(this.A,function(a){return!this.contains(a)},this))};
g.h.hE=function(){return(0,g.Hd)(this.ke(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.iE=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new d7(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.z)(function(a){g.Ze(f);d(m7(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ze(f);e(a)});
f.start();return(0,g.z)(f.stop,f)};
g.h.UU=function(a,b,c,d){g.lE(W6(this.C,"/pairing/get_screen"),{method:"POST",Lb:{pairing_code:a},timeout:5E3,Hb:(0,g.z)(function(a,d){var e=new a6(d.screen||{});if(!e.name||hCa(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);hCa(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(m7(this,e))},this),
onError:(0,g.z)(function(a){d(Error("pairing request failed: "+a.status))},this),
wd:(0,g.z)(function(){d(Error("pairing request timed out."))},this)})};
g.h.U=function(){g.Ze(this.o);g.Ze(this.l);l7.Z.U.call(this)};
g.h.RI=function(){iCa(this);this.P("screenChange");this.l.update()};
l7.prototype.dispose=l7.prototype.dispose;g.A(o7,g.FF);g.h=o7.prototype;g.h.No=function(a){this.o=a;this.P("sessionScreen",this.o)};
g.h.qe=function(a){this.ha()||(a&&p7(this,""+a),this.o=null,this.P("sessionScreen",null))};
g.h.info=function(a){Z6(this.M,a)};
g.h.kE=function(){return null};
g.h.Cu=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.z)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.z)(function(){p7(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.U=function(){this.Cu("");o7.Z.U.call(this)};g.A(q7,o7);g.h=q7.prototype;g.h.Bu=function(a){if(this.g){if(this.g==a)return;p7(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);kCa(this)};
g.h.Kj=function(a){this.info("launchWithParams no-op for Cast: "+g.yg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.z)(function(){this.qe()},this),(0,g.z)(function(){this.qe(Error("Failed to stop receiver app."))},this)):this.qe(Error("Stopping cast device witout session."))};
g.h.Cu=g.y;g.h.U=function(){this.info("disposeInternal");g.QD(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;q7.Z.U.call(this)};
g.h.ZS=function(a,b){if(!this.ha())if(b){var c=g.Tw(b);if(g.Ba(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.yg(c));switch(d){case "mdxSessionStatus":jCa(this,c.screenId);break;default:p7(this,"Unknown youtube message: "+d)}}else p7(this,"Unable to parse message.")}else p7(this,"No data in message.")};
g.h.Zx=function(a,b,c,d){gCa(this.H,this.l.label,a,this.l.friendlyName,(0,g.z)(function(e){e?b(e):0<=d?(p7(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.OD((0,g.z)(this.Zx,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.kE=function(){return this.g};
g.h.VU=function(a){this.ha()||a||(p7(this,"Cast session died."),this.qe())};g.A(r7,o7);g.h=r7.prototype;g.h.Bu=function(a){this.A=a;this.A.addUpdateListener(this.K)};
g.h.Kj=function(a){this.B=a;this.D()};
g.h.stop=function(){this.g();this.g=g.y;g.QD(this.C);this.A?this.A.stop((0,g.z)(this.qe,this,null),(0,g.z)(this.qe,this,"Failed to stop DIAL device.")):this.qe()};
g.h.U=function(){this.g();this.g=g.y;g.QD(this.C);this.A&&this.A.removeUpdateListener(this.K);this.A=null;r7.Z.U.call(this)};
g.h.YU=function(a){this.ha()||a||(p7(this,"DIAL session died."),this.g(),this.g=g.y,this.qe())};
g.h.ls=function(a){this.I=e6();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,mCa(this));a(b);lCa(this)}else this.D=(0,g.z)(function(){g.QD(this.C);this.D=g.y;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,mCa(this));a(b);lCa(this)},this),this.C=g.OD((0,g.z)(function(){this.D()},this),100)};
g.h.gK=function(a,b,c){gCa(this.H,this.F.receiver.label,a,this.l.friendlyName,(0,g.z)(function(a){a&&a.token?(this.No(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.ls(b,c)},this),(0,g.z)(function(a){p7(this,"Failed to get DIAL screen: "+a);
this.ls(b,c)},this))};g.A(s7,o7);s7.prototype.stop=function(){this.qe()};
s7.prototype.Bu=g.y;s7.prototype.Kj=function(){g.QD(this.g);this.g=window.NaN;var a=g6(this.H.ke(),this.l.label);a?this.No(a):this.qe(Error("No such screen"))};
s7.prototype.U=function(){g.QD(this.g);this.g=window.NaN;s7.Z.U.call(this)};g.A(t7,g.FF);g.h=t7.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.D);this.F||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.z)(this.TB,this),(0,g.z)(this.GR,this),d,e);c.customDialLaunchCallback=(0,g.z)(this.DP,this);window.chrome.cast.initialize(c,
(0,g.z)(function(){this.ha()||(window.chrome.cast.addReceiverActionListener(this.A),UBa(),this.l.subscribe("onlineScreenChange",(0,g.z)(this.jE,this)),this.o=oCa(this),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.gc("Failed to set initial custom receivers: "+g.yg(a))},this)),this.P("yt-remote-cast2-availability-change",v7(this)),b(!0))},this),(0,g.z)(function(a){this.gc("Failed to initialize API: "+g.yg(a));
b(!1)},this))};
g.h.RT=function(a,b){u7("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)u7("Unsetting old screen status: "+this.g.l.friendlyName),w7(this,null)}if(a&&b){if(!this.g){c=g6(this.l.ke(),a);if(!c){u7("setConnectedScreenStatus: Unknown screen.");return}var d=nCa(this,c);d||(u7("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(a){this.gc("Failed to set initial custom receivers: "+g.yg(a))},this)));
u7("setConnectedScreenStatus: new active receiver: "+d.friendlyName);w7(this,new s7(this.l,d),!0)}this.g.Cu(b)}else u7("setConnectedScreenStatus: no screen.")};
g.h.ST=function(a){this.ha()?this.gc("Setting connection data on disposed cast v2"):this.g?this.g.Kj(a):this.gc("Setting connection data without a session")};
g.h.XU=function(){this.ha()?this.gc("Stopping session on disposed cast v2"):this.g?(this.g.stop(),w7(this,null)):u7("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.z)(this.TB,this),(0,g.z)(this.bS,this))};
g.h.U=function(){this.l.unsubscribe("onlineScreenChange",(0,g.z)(this.jE,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Ua(g.x("yt.mdx.remote.debug.handlers_")||[],RBa);g.Ze(this.g);t7.Z.U.call(this)};
g.h.gc=function(a){Z6("Controller",a)};
g.h.UB=function(a,b){this.g==a&&(b||w7(this,null),this.P("yt-remote-cast2-session-change",b))};
g.h.CR=function(a,b){if(!this.ha())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),u7("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)u7("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{u7("onReceiverAction_: Casting to active receiver.");this.g.o&&this.P("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:w7(this,
new s7(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:w7(this,new r7(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:w7(this,new q7(this.l,a));break;default:this.gc("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.gc("Stopping receiver w/o session: "+a.friendlyName)}else this.gc("onReceiverAction_ called without receiver.")};
g.h.DP=function(a){if(this.ha())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.gc("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.gc("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return u7("Reselecting dial screen."),
this.P("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.gc('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);w7(this,new r7(this.l,b,this.C))}b=this.g;b.F=a;return b.F.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.z)(b.gK,b,(b.F.extraData||{}).screenId||null)):new window.Promise((0,g.z)(b.ls,b))};
g.h.TB=function(a){if(!this.ha()){u7("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)u7("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),w7(this,new q7(this.l,b),!0);else{this.gc("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=g6(this.l.ke(),c.label);
d&&b6(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(u7("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ze(this.g),this.g=new q7(this.l,b),this.g.subscribe("sessionScreen",(0,g.z)(this.UB,this,this.g)),this.g.Kj(null));this.g.Bu(a)}}};
g.h.WU=function(){return this.g?this.g.kE():null};
g.h.bS=function(a){this.ha()||(this.gc("Failed to estabilish a session: "+g.yg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&w7(this,null))};
g.h.GR=function(a){u7("Receiver availability updated: "+a);if(!this.ha()){var b=v7(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;v7(this)!=b&&this.P("yt-remote-cast2-availability-change",v7(this))}};
g.h.jE=function(){this.ha()||(this.o=oCa(this),u7("Updating custom receivers: "+g.yg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.y,(0,g.z)(function(){this.gc("Failed to set custom receivers.")},this)),this.P("yt-remote-cast2-availability-change",v7(this)))};
t7.prototype.setLaunchParams=t7.prototype.ST;t7.prototype.setConnectedScreenStatus=t7.prototype.RT;t7.prototype.stopSession=t7.prototype.XU;t7.prototype.getCastSession=t7.prototype.WU;t7.prototype.requestSession=t7.prototype.requestSession;t7.prototype.init=t7.prototype.init;t7.prototype.dispose=t7.prototype.dispose;var C7=[];g.h=H7.prototype;
g.h.reset=function(a){this.listId="";this.index=-1;this.videoId="";I7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.Kf=a.hasPrevious,this.hasNext=a.hasNext,this.F=a.playerTime,this.D=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.H=a.duration,this.I=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
g.h.kb=function(){return 1==this.g};
g.h.isAdPlaying=function(){return 1081==this.g};
g.h.getDuration=function(){return this.C?this.H+J7(this):this.H};
g.h.clone=function(){return new H7(N7(this))};g.A(P7,g.FF);g.h=P7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.y,V7(this,"play")):U7(this,"play"),T7(this,1,L7(Q7(this))),this.P("remotePlayerChange")):R7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.y,V7(this,"pause")):U7(this,"pause"),T7(this,2,L7(Q7(this))),this.P("remotePlayerChange")):R7(this,this.pause)};
g.h.fE=function(a){if(1==this.g){if(this.l){var b=Q7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=b.kb()||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.y,V7(this,"seekTo",{newTime:a}))}else U7(this,"seekTo",{newTime:a});T7(this,3,a);this.P("remotePlayerChange")}else R7(this,g.Ea(this.fE,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.y,V7(this,"stopVideo")):U7(this,"stopVideo");var a=Q7(this);a.index=-1;a.videoId="";I7(a);S7(this,a);this.P("remotePlayerChange")}else R7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=Q7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.z)(function(){Z6("CP","set receiver volume: "+d)},this),(0,g.z)(function(){this.gc("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.z)(function(){Z6("CP","set receiver muted: "+b)},this),(0,g.z)(function(){this.gc("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);U7(this,"setVolume",e)}c.muted=b;c.volume=a;S7(this,c)}else R7(this,g.Ea(this.setVolume,a,b))};
g.h.eD=function(a,b){if(1==this.g){var c=Q7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.yg(b.style),g.dc(d,c.l));U7(this,"setSubtitlesTrack",d);S7(this,c)}else R7(this,g.Ea(this.eD,a,b))};
g.h.rv=function(a,b){if(1==this.g){U7(this,"setAudioTrack",{videoId:a,audioTrackId:b.Pb.id});var c=Q7(this);c.audioTrackId=b.Pb.id;S7(this,c)}else R7(this,g.Ea(this.rv,a,b))};
g.h.eE=function(a,b){if(1==this.g){if(a&&b){var c=Q7(this);M7(c,a,b);S7(this,c)}U7(this,"previous")}else R7(this,g.Ea(this.eE,a,b))};
g.h.dE=function(a,b){if(1==this.g){if(a&&b){var c=Q7(this);M7(c,a,b);S7(this,c)}U7(this,"next")}else R7(this,g.Ea(this.dE,a,b))};
g.h.tx=function(){1==this.g?U7(this,"dismissAutoplay"):R7(this,this.tx)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.P("proxyStateChange",a,this.g)}P7.Z.dispose.call(this)};
g.h.U=function(){BCa(this);this.A=null;this.B.clear();O7(this,null);P7.Z.U.call(this)};
g.h.tv=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.P("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)g.hC(this.B).apply(this);else 3==a&&this.dispose()}};
g.h.xR=function(a,b){this.P(a,b)};
g.h.ZO=function(a){if(!a)this.Fl(null),O7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=Q7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)Z6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,S7(this,b)}};
g.h.Fl=function(a){Z6("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.F);if(this.l=a)this.l.addUpdateListener(this.F),CCa(this),this.P("remotePlayerChange")};
g.h.YO=function(a){a?(CCa(this),this.P("remotePlayerChange")):this.Fl(null)};
g.h.mP=function(){var a=yCa();a&&O7(this,a)};
g.h.gc=function(a){Z6("CP",a)};g.A(W7,g.FF);g.h=W7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Za.listId=c);this.Za.videoId=d;this.Za.index=k||0;this.Za.state=3;K7(this.Za,m);this.A="UNSUPPORTED";X7("Connecting with setPlaylist and params: "+g.yg(l));this.g.connect({method:"setPlaylist",params:g.yg(l)},a,YAa())}else X7("Connecting without params"),
this.g.connect({},a,YAa());ECa(this)};
g.h.dispose=function(){this.ha()||(this.P("beforeDispose"),Y7(this,3));W7.Z.dispose.call(this)};
g.h.U=function(){Z7(this);a8(this);$7(this);g.QD(this.H);this.H=window.NaN;g.QD(this.I);this.I=window.NaN;this.o=null;g.qF(this.V);this.V.length=0;this.g.dispose();W7.Z.U.call(this);this.A=this.D=this.l=this.Za=this.g=null};
g.h.rI=function(){this.C(2)};
g.h.dP=function(){X7("Channel opened");this.N&&(this.N=!1,$7(this),this.M=g.OD((0,g.z)(function(){X7("Timing out waiting for a screen.");this.C(1)},this),15E3));
bBa(OBa(this.g),this.X)};
g.h.aP=function(){X7("Channel closed");(0,window.isNaN)(this.B)?l6(!0):l6();this.dispose()};
g.h.bP=function(a){l6();(0,window.isNaN)(this.F())?(X7("Channel error: "+a+" without reconnection"),this.dispose()):(this.N=!0,X7("Channel error: "+a+" with reconnection in "+this.F()+" ms"),Y7(this,2))};
g.h.cP=function(a){a.params?X7("Received: action="+a.action+", params="+g.yg(a.params)):X7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.Tw(a.params.devices);this.l=(0,g.H)(a,function(a){return new $5(a)});
a=!!g.Ka(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
HCa(this,a);break;case "loungeScreenDisconnected":g.Va(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
HCa(this,!1);break;case "remoteConnected":var b=new $5(g.Tw(a.params.device));g.Ka(this.l,function(a){return b?a.id==b.id:!1})||g.Sa(this.l,b);
break;case "remoteDisconnected":b=new $5(g.Tw(a.params.device));g.Va(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":JCa(this,a);break;case "nowPlaying":LCa(this,a);break;case "onStateChange":KCa(this,a);break;case "onAdStateChange":MCa(this,a);break;case "onVolumeChanged":NCa(this,a);break;case "onSubtitlesTrackChanged":ICa(this,a);break;case "nowAutoplaying":OCa(this,a);break;case "autoplayDismissed":this.P("autoplayDismissed");break;case "autoplayUpNext":this.D=a.params.videoId||null;this.P("autoplayUpNext",this.D);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.P("autoplayModeChange",this.A);"DISABLED"==this.A&&this.P("autoplayDismissed");break;case "onHasPreviousNextChanged":PCa(this,a);break;case "requestAssistedSignIn":this.P("assistedSignInRequested",a.params.authCode);break;default:X7("Unrecognized action: "+a.action)}};
g.h.BT=function(){if(this.o){var a=this.o;this.o=null;this.Za.videoId!=a&&b8(this,"getNowPlaying")}};
W7.prototype.subscribe=W7.prototype.subscribe;W7.prototype.unsubscribeByKey=W7.prototype.Nd;W7.prototype.da=function(){var a=3;this.ha()||(a=0,(0,window.isNaN)(this.F())?U6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
W7.prototype.getProxyState=W7.prototype.da;W7.prototype.C=function(a){X7("Disconnecting with "+a);Z7(this);this.P("beforeDisconnect",a);1==a&&l6();PBa(this.g,a);this.dispose()};
W7.prototype.disconnect=W7.prototype.C;W7.prototype.ca=function(){var a=this.Za;this.o&&(a=this.Za.clone(),M7(a,this.o,a.index));return N7(a)};
W7.prototype.getPlayerContextData=W7.prototype.ca;
W7.prototype.la=function(a){var b=new H7(a);b.videoId&&b.videoId!=this.Za.videoId&&(this.o=b.videoId,g.QD(this.H),this.H=g.OD((0,g.z)(this.BT,this),5E3));var c=[];this.Za.listId==b.listId&&this.Za.videoId==b.videoId&&this.Za.index==b.index||c.push("remoteQueueChange");this.Za.g==b.g&&this.Za.volume==b.volume&&this.Za.muted==b.muted&&L7(this.Za)==L7(b)&&g.yg(this.Za.l)==g.yg(b.l)||c.push("remotePlayerChange");this.Za.reset(a);(0,g.B)(c,function(a){this.P(a)},this)};
W7.prototype.setPlayerContextData=W7.prototype.la;W7.prototype.W=function(){var a=this.g.C.id,b=g.Ka(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
W7.prototype.getOtherConnectedRemoteId=W7.prototype.W;W7.prototype.F=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.G)():window.NaN};
W7.prototype.getReconnectTimeout=W7.prototype.F;W7.prototype.Y=function(){return this.A||"UNSUPPORTED"};
W7.prototype.getAutoplayMode=W7.prototype.Y;W7.prototype.ba=function(){return this.D||""};
W7.prototype.getAutoplayVideoId=W7.prototype.ba;W7.prototype.oa=function(){if(!(0,window.isNaN)(this.F())){var a=this.g.l;g.Xt(a.g);a.start()}};
W7.prototype.reconnect=W7.prototype.oa;W7.prototype.fa=function(a,b){b8(this,a,b);GCa(this)};
W7.prototype.sendMessage=W7.prototype.fa;g.A(c8,c7);g.h=c8.prototype;g.h.ke=function(a){return this.dd.$_gs(a)};
g.h.contains=function(a){return!!this.dd.$_c(a)};
g.h.get=function(a){return this.dd.$_g(a)};
g.h.start=function(){this.dd.$_st()};
g.h.add=function(a,b,c){this.dd.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.dd.$_r(a,b,c)};
g.h.Ep=function(a,b,c,d){this.dd.$_un(a,b,c,d)};
g.h.U=function(){for(var a=0,b=this.l.length;a<b;++a)this.dd.$_ubk(this.l[a]);this.l.length=0;this.dd=null;c8.Z.U.call(this)};
g.h.TU=function(){this.P("screenChange")};
g.h.YQ=function(){this.P("onlineScreenChange")};
l7.prototype.$_st=l7.prototype.start;l7.prototype.$_gspc=l7.prototype.UU;l7.prototype.$_gsppc=l7.prototype.iE;l7.prototype.$_c=l7.prototype.contains;l7.prototype.$_g=l7.prototype.get;l7.prototype.$_a=l7.prototype.add;l7.prototype.$_un=l7.prototype.Ep;l7.prototype.$_r=l7.prototype.remove;l7.prototype.$_gs=l7.prototype.ke;l7.prototype.$_gos=l7.prototype.hE;l7.prototype.$_s=l7.prototype.subscribe;l7.prototype.$_ubk=l7.prototype.Nd;var d8=null,e8=null,t8=null,i8=[];g.p(u8,g.K);g.h=u8.prototype;
g.h.U=function(){g.K.prototype.U.call(this);this.A.stop();this.B.stop();this.K.stop();this.N();this.g.unsubscribe("proxyStateChange",this.RB,this);this.g.unsubscribe("remotePlayerChange",this.Il,this);this.g.unsubscribe("remoteQueueChange",this.Oo,this);this.g.unsubscribe("autoplayUpNext",this.nB,this);this.g.unsubscribe("previousNextChange",this.OB,this);this.g.unsubscribe("nowAutoplaying",this.GB,this);this.g.unsubscribe("autoplayDismissed",this.mB,this);this.g=this.F=null};
g.h.rA=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(x8(this)){if(!Q7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":Q7(this.g).kb()?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.I.sj(c[0],c[1]);break;case "control_subtitles_set_track":y8(this,c[0]);break;case "control_set_audio_track":c=c[0],x8(this)&&this.g.rv(this.l.ea(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.getCurrentTime();z8(this,0==c?void 0:c);break;case "control_seek":z8(this,c[0]);break;case "control_subtitles_set_track":y8(this,c[0]);break;case "control_set_audio_track":c=c[0],x8(this)&&this.g.rv(this.l.ea(1).videoId,c)}};
g.h.XO=function(a){this.K.nI(a)};
g.h.wU=function(a){this.rA("control_subtitles_set_track",g.Xb(a)?null:a)};
g.h.qD=function(){var a=this.l.zc("captions","track");g.Xb(a)||y8(this,a)};
g.h.EB=function(a){if(x8(this)){this.g.unsubscribe("remotePlayerChange",this.Il,this);var b=Math.round(a.volume);a=!!a.muted;var c=Q7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.M.start();this.g.subscribe("remotePlayerChange",this.Il,this)}};
g.h.qQ=function(){g.Xb(this.C)||aDa(this,this.C);this.D=!1};
g.h.RB=function(a,b){this.B.stop();2==b&&this.nD()};
g.h.Il=function(){if(x8(this)){this.A.stop();var a=Q7(this.g);switch(a.g){case 1081:case 1:w8(this,new g.TO(8));this.mD();break;case 1085:case 3:w8(this,new g.TO(9));break;case 1083:case 0:w8(this,new g.TO(2));this.I.stop();v8(this,this.l.ea().lengthSeconds);break;case 1084:w8(this,new g.TO(4));break;case 2:w8(this,new g.TO(4));v8(this,L7(a));break;case -1:w8(this,new g.TO(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.V("YTP_MDX_PLAYER_ERROR")},w8(this,new g.TO(128,a))}a=Q7(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,aDa(this,a));a=Q7(this.g);-1==a.volume||Math.round(this.l.getVolume())==a.volume&&this.l.isMuted()==a.muted||this.M.isActive()||this.TD()}else $Ca(this)};
g.h.OB=function(){this.l.P("mdxpreviousnextchange")};
g.h.Oo=function(){x8(this)||$Ca(this)};
g.h.zH=function(){this.g.tx()};
g.h.nB=function(a){a&&(a=g.lE("/watch_queue_ajax",{method:"GET",Zc:{action_get_watch_queue_item:1,video_id:a},Hb:(0,g.z)(this.AS,this)}))&&(this.N=(0,g.z)(a.abort,a))};
g.h.AS=function(a,b){var c=new g.UN({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.P("mdxautoplayupnext",c)};
g.h.GB=function(a){(0,window.isNaN)(a)||this.l.P("mdxnowautoplaying",a)};
g.h.mB=function(){this.l.P("mdxautoplaycanceled")};
g.h.bN=function(a,b){-1==Q7(this.g).g?z8(this,a):b&&this.g.fE(a)};
g.h.TD=function(){if(x8(this)){var a=Q7(this.g);this.o.Ba(this.V);a.muted?this.l.mute():this.l.Vf();this.l.setVolume(a.volume);this.V=this.o.O(this.l,"onVolumeChange",this.EB)}};
g.h.mD=function(){this.A.stop();if(!this.g.ha()){var a=Q7(this.g);a.kb()&&w8(this,new g.TO(8));v8(this,L7(a));this.A.start()}};
g.h.nD=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.p(A8,g.W);A8.prototype.A=function(a){cDa(this,a.state)};g.p(B8,g.GZ);B8.prototype.I=function(){var a=this.l.zc("remote","receivers");a&&1<a.length&&!this.l.zc("remote","quickCast")?(this.F=g.jb(a,this.B,this),g.HZ(this,(0,g.H)(a,this.B)),a=this.l.zc("remote","currentReceiver"),this.pf(this.B(a)),this.enable(!0)):this.enable(!1)};
B8.prototype.B=function(a){return a.key};
B8.prototype.nf=function(a){return"cast-selector-receiver"==a?g.V("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
B8.prototype.td=function(a){g.GZ.prototype.td.call(this,a);this.l.Kd("remote","currentReceiver",this.F[a]);this.A.Qb()};g.p(C8,g.qV);g.h=C8.prototype;g.h.create=function(){UCa(g.nM(g.Y(this.g)));this.C.push(g.QF("yt-remote-before-disconnect",this.TO,this));this.C.push(g.QF("yt-remote-connection-change",this.HR,this));this.C.push(g.QF("yt-remote-receiver-availability-change",this.PB,this));this.C.push(g.QF("yt-remote-auto-connect",this.FR,this));this.C.push(g.QF("yt-remote-receiver-resumed",this.ER,this));this.PB()};
g.h.load=function(){this.g.qt();g.qV.prototype.load.call(this);this.B=new u8(this,this.g,this.l);var a=(a=ZCa())?a.currentTime:0;var b=s8()?new P7(n8(),void 0):null;0==a&&b&&(a=L7(Q7(b)));0!=a&&(this.H=a||0,this.g.P("progresssync",a,void 0));bDa(this,this.D,this.D);g.R_(this.g.app,6)};
g.h.unload=function(){this.g.P("mdxautoplaycanceled");this.A=this.o;g.$e(this.B,this.l);this.l=this.B=null;g.qV.prototype.unload.call(this);g.R_(this.g.app,5)};
g.h.U=function(){g.RF(this.C);g.qV.prototype.U.call(this)};
g.h.xl=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.rA.apply(this.B,[].concat([a],g.qa(c)))};
g.h.jI=function(){return this.loaded?this.B.suggestion:null};
g.h.Kf=function(){return this.l?Q7(this.l).Kf:!1};
g.h.hasNext=function(){return this.l?Q7(this.l).hasNext:!1};
g.h.getCurrentTime=function(){return this.H};
g.h.PM=function(){var a=Q7(this.l),b=this.g.ea();return{allowSeeking:this.g.fd(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.getCurrentTime(),displayedStart:-1,duration:a.getDuration(),ingestionTime:a.C?a.A+J7(a):a.A,isPeggedToLive:1>=(a.C?a.o+J7(a):a.o)-this.getCurrentTime(),loaded:a.I,seekableEnd:a.C?a.o+J7(a):a.o,seekableStart:0<a.B?a.B+J7(a):a.B}};
g.h.QM=function(){this.l&&this.l.dE()};
g.h.RM=function(){this.l&&this.l.eE()};
g.h.TO=function(a){1==a&&(this.I=this.l?Q7(this.l):null)};
g.h.HR=function(){var a=s8()?new P7(n8(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.I=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Ze(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.I)&&a.videoId==this.g.ea().videoId&&this.g.Tz(a.videoId,L7(a)));this.g.P("videodatachange","newdata",this.g.ea(),3)};
g.h.PB=function(){this.F=[this.o].concat(WCa());var a=o8()||this.o;D8(this,a);this.g.sa("onMdxReceiversChange")};
g.h.FR=function(){var a=o8();D8(this,a)};
g.h.ER=function(){this.A=o8()};
g.h.OM=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.F;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?F7():D8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.F.length&&"cast-selector-receiver"==this.F[1].key?(b&&F7(),!0):!1}};
g.h.SM=function(){U7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.Qc=function(){return!1};g.bY.remote=C8;})(_yt_player);
